---
# tasks file for postgresql

- name: Adding PostgreSQL APT repository key
  become: yes
  apt_key:
    id: ACCC4CF8
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: Add PostgreSQL official APT repository
  become: yes
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main"

- name: Ensure PostgreSQL packages are installed
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - "postgresql-{{postgresql_version}}"
    - "postgresql-contrib-{{postgresql_version}}"
    - libpq-dev

- name: Ensure PostgreSQL dependencies are installed for the Ansible module
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ postgresql_python_library }}"

# PostgreSQL Locales
- name: Ensure all configured locales are present
  become: yes
  locale_gen:
    name: "{{ postgresql_locale }}"
    state: present
  register: locale_gen_result

- name: Force-restart PostgreSQL after new locales are generated
  service:
    name: postgresql
    state: restarted
  when: locale_gen_result.changed

# Configure PostgreSQL
- name: Configure global settings
  become: yes
  template:
    src: postgresql.conf.j2
    dest: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
  notify: reload postgresql

- name: Configure host based authentication (if entries are configured)
  become: yes
  template:
    src: pg_hba.conf.j2
    dest: "/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: 0600
  notify: restart postgresql

# Enable tasks
- name: Ensure PostgreSQL is started and enabled on boot
  become: yes
  service:
    enabled: yes
    name: postgresql
    state: started

# Database tasks
- name: Ensure Database user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ postgresql_root_user }}"
    password: "{{ postgresql_root_password }}"
    role_attr_flags: "SUPERUSER,CREATEROLE,CREATEDB,INHERIT,login"
    state: present
