---
# defaults file for dotfiles

# Default dotfiles user.
dotfiles_user: "{{ mimetic_user | default(ansible_env.SUDO_USER) }}"

# Default dotfiles home.
dotfiles_home: "{{ mimetic_home | default(ansible_env.HOME) }}"

# Default ssh public & private key files.
dotfiles_ssh_key: "{{ dotfiles_home }}/.ssh/id_rsa"

# Default dotfiles path.
dotfiles_path: .dotfiles

# Default dotfiles Github repo.
dotfiles_repo: git@github.com:michaelcapx/dotfiles.git
