---
# tasks file for redis

- name: Add PPA for Redis
  apt_repository:
    repo: ppa:chris-lea/redis-server
    state: present
    update_cache: yes

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400
  changed_when: false

# Setup/install tasks
- name: Ensure Redis is installed
  apt:
    name: "{{ redis_package }}"
    state: present

- name: Configure Redis
  lineinfile:
    dest: "{{ redis_conf_path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: 'bind 127\.0\.0\.1', line: "bind 127.0.0.1" }

- name: "Ensure Redis is {{ redis_start | ternary('started','stopped') }}"
  service:
    name: "{{ redis_daemon }}"
    state: "{{ redis_start | ternary('restarted','stopped') }}"
    enabled: "{{ redis_service_enabled }}"
