---
# tasks file for redis

# Redis install
- name: Configure the Redis PPA
  apt_repository:
    repo: ppa:chris-lea/redis-server
    state: present
    update_cache: yes

- name: Ensure Redis is installed
  apt:
    name: "{{ redis_package }}"
    state: present
    update_cache: yes

# Redis configuration
- name: Ensure Redis is configured
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    mode: 0644
  notify: restart redis

- name: Ensure Redis is running and enabled on boot
  service:
    name: "{{ redis_daemon }}"
    state: started
    enabled: yes
