---
# tasks file for nginx

- name: Add PPA for Nginx
  apt_repository:
    repo: "ppa:nginx/{{ nginx_ppa_version }}"
    state: present
    update_cache: yes
  register: nginx_ppa_added

- name: Ensure nginx is installed
  apt:
    name: "{{ nginx_package_name }}"
    state: latest

- name: Remove the default configuration
  file:
    path: "{{ item }}"
    state: absent
  with_items :
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default
  notify: restart nginx

- name: Copy fastcgi_params
  template:
    src: fastcgi_params
    dest: /etc/nginx/fastcgi_params

- name: Configure nginx user
  lineinfile:
    dest: /etc/nginx/nginx.conf
    regexp: "^{{ item.param }}"
    line: "{{ item.param }} {{ item.value }};"
  with_items :
    - { param: user, value: "{{ nginx_user }}" }
    - { param: server_names_hash_bucket_size, value: "{{ nginx_server_hash_bucket_size }}" }
  notify: restart nginx

- name: Ensure nginx is started and enabled to start at boot
  service:
    name: nginx
    state: started
    enabled: yes
