---
dependencies: []

galaxy_info:
  author:   PolyAlloy
  description: A basic role providing some common tools and system configurations.
  license: MIT
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
      - xenial
  galaxy_tags:
    - chromebook
    - galliumos
    - system
    - development
    - desktop
    - common
