---
dependencies: []

galaxy_info:
  author: PolyAlloy
  description: Installs Python and pip packages.
  license: MIT
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
      - xenial
  galaxy_tags:
    - chromebook
    - galliumos
    - system
    - development
    - desktop
    - python
