---
# tasks file for firefox

# Installation Prerequisites
- name: Delete firefox profiles directory
  file:
    path: "{{ firefox_config }}"
    state: absent

- name: Ensure firefox dependencies are installed
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ firefox_dependencies | list }}"
  when: firefox_dependencies | length

# Install Packages
- name: Add Firefox Next repository
  become: yes
  apt_repository:
    repo: "{{ firefox_ppa }}"
    state: present
    validate_certs: yes
    update_cache: yes
  register: firefox_repo

- name: Update apt cache if repo was added
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: firefox_repo.changed

- name: Ensure firefox packages are installed
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ firefox_packages | list }}"
  when: firefox_packages | length

# Configure Firefox Profiles
- name: Create firefox profiles
  firefox_profile:
    name: "{{ item.name }}"
    state: present
  become: true
  become_user: "{{ firefox_user }}"
  with_items: "{{ firefox_profiles }}"
  register: firefox_profile_register

# Install Firefox Global Extensions
- name: Ensure firefox global extension directory exists
  become: yes
  file:
    path: "{{ firefox_addons_dir }}"
    state: directory

- name: Install firefox global extensions
  become: yes
  get_url:
    url: "{{ item.url }}"
    dest: "{{ firefox_addons_dir }}/{{ item.guid }}.xpi"
    timeout: 30
    mode: 0644
  with_items: "{{ firefox_global_addons }}"
  ignore_errors: true
  register: dl_firefox_ext
  until: dl_firefox_ext is succeeded
  retries: 10
  delay: 5

# Set System Firefox Preferences
#  FIXME
# - name: Copy firefox system preferences
#   become: yes
#   copy:
#     src: "syspref.js"
#     dest: "{{ firefox_system_prefs }}"
#     mode: 0644

# Set Global Firefox Preferences
# - name: Set global firefox preferences
#   become: yes
#   get_url:
#     url: "https://raw.githubusercontent.com/pyllyukko/user.js/5f3a460167fcfb8e4d4152b03c319fd002de8dc0/user.js"
#     checksum: "sha256:9344793e14856f51332d9e6e2d8fb9c579da78c5af1a57d09ff62a817d2cc3d5"
#     dest: "{{ firefox_global_prefs }}"
#     timeout: 30
#     mode: 0644
#     backup: yes
#     force: yes
#   when: firefox_harden
#   register: dl_firefox_prefs
#   until: dl_firefox_prefs | succeeded
#   retries: 10
#   delay: 5

# - name: Configure global firefox preferences as default
#   become: yes
#   replace:
#     dest: "{{ firefox_global_prefs }}"
#     regexp: 'user_pref\('
#     replace: 'pref('
#     backup: yes
#   when: firefox_harden

# Configure Firefox Preferences
# - name: Set firefox user preferences
#   template:
#     src: user.js.j2
#     dest: "{{ item.profile_path }}/user.js"
#   with_items: "{{ firefox_profile_register.results }}"
#   when: firefox_preferences is defined and firefox_profile_register.profile_path is defined
#   become: true
#   become_user: "{{ firefox_user }}"
