---
# defaults file for git

# Determines the state for packages installed on the system. Available values are `present` or `latest`.
git_apt_state: present

# Array of git packages to install.
git_packages:
  - git
  - git-core
  - git-svn

# Git configuration object.
git_config:
  user:
    name: "{{ pbook_name | default(none) }}"
    email: "{{ pbook_email | default(none) }}"
  color:
    branch: auto
    diff: auto
    interactive: auto
    status: auto
    ui: true
  core:
    editor: nano
    excludesfile: "{{ ansible_env.HOME }}/.gitexcludesfile"
  credential:
    helper: cache
  push:
    default: simple
  alias:
    br: branch
    ci: commit
    clo: clone
    co: checkout
    lg: log -M --decorate --graph --oneline
    pur: pull --rebase
    rc: rebase --continue
    st: status
    sth: stash

# Array of filenames and patterns for git to globally ignore.
git_ignore:
  - "*.log"
  - ".vagrant"
  # OS generated files
  - ".DS_Store"
  - ".DS_Store?"
  - "._*"
  - ".Spotlight-V100"
  - ".Trashes"
  - "Icon?"
  - "ehthumbs.db"
  - "Thumbs.db"
  # ide
  - "~*"
  - ".idea/"

# Array of name and key values for known git hosts.
git_known_hosts:
  - name: github.com
    key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
  - name: bitbucket.org
    key: bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
  - name: gitlab.com
    key: gitlab.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf
  - name: gitlab.com
    key: gitlab.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsj2bNKTBSpIYDEGk9KxsGh3mySTRgMtXL583qmBpzeQ+jqCMRgBqB98u3z++J1sKlXHWfM9dyhSevkMwSbhoR8XIq/U0tCNyokEi/ueaBMCvbcTHhO7FcwzY92WK4Yt0aGROY5qX2UKSeOvuP4D6TPqKF1onrSzH9bx9XUf2lEdWT/ia1NEKjunUqu1xOB/StKDHMoX4/OKyIzuS0q/T1zOATthvasJFoPrAjkohTyaDUz2LN5JoH839hViyEG82yB+MjcFV5MU3N1l1QL3cVUCh93xSaua1N85qivl+siMkPGbO5xR/En4iEY6K2XPASUEMaieWVNTRCtJ4S8H+9

# Github/BitBucket Keys
git_github_user: "{{ pbook_github_user | default('') }}"
git_github_password: "{{ pbook_github_password | default('') }}"
git_bitbucket_user: "{{ pbook_bitbucket_user | default('') }}"
git_bitbucket_password: "{{ pbook_bitbucket_password | default('') }}"
