---
# defaults file for git

# Array of git packages to install.
git_packages:
  - git
  - git-core
  - git-svn
  - git-extras

# Default git user.
git_user: "{{ mimetic_user | default(ansible_env.SUDO_USER) }}"

# Default git home.
git_home: "{{ mimetic_home | default(ansible_env.HOME) }}"

# Github/BitBucket Keys
git_github_user: "{{ mimetic_github_user | default('') }}"
git_github_password: "{{ mimetic_github_password | default('') }}"
git_bitbucket_user: "{{ mimetic_bitbucket_user | default('') }}"
git_bitbucket_password: "{{ mimetic_bitbucket_password | default('') }}"

# Gitconfig user name.
git_config_name: "{{ mimetic_name | default(null) }}"

# Gitconfig user email.
git_config_email: "{{ mimetic_email | default(null) }}"

# Gitconfig editor
git_config_editor: nano

# Location of .gitignore file.
git_ignore_file: "/home/{{ git_user }}/.gitignore"

# Git SSH keyfile
git_ssh_keyfile: "{{ git_home }}/.ssh/id_rsa.pub"
