---
# defaults file for git

# Array of git packages to install.
git_packages:
  - git
  - git-core
  - git-svn
  - git-extras

# Default git user.
git_user: "{{ master_user | default(ansible_env.SUDO_USER) }}"

# Default git home.
git_home: "{{ master_home | default(ansible_env.HOME) }}"

# Github/BitBucket Keys
git_github_user: "{{ master_github_user | default('') }}"
git_github_password: "{{ master_github_password | default('') }}"
git_bitbucket_user: "{{ master_bitbucket_user | default('') }}"
git_bitbucket_password: "{{ master_bitbucket_password | default('') }}"

# Gitconfig user name.
git_config_name: "{{ master_name | default(null) }}"

# Gitconfig user email.
git_config_email: "{{ master_email | default(null) }}"

# Gitconfig editor
git_config_editor: nano

# Location of .gitignore file.
git_ignore_file: "/home/{{ git_user }}/.gitignore"

# Git SSH keyfile
git_ssh_keyfile: "{{ git_home }}/.ssh/id_rsa.pub"
