---
# tasks file for sqlite

- name: Install sqlite packages
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items: "{{ sqlite_packages }}"

- name: Create sqlite directory
  file:
    path: "{{ sqlite_dir }}"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0755

- name: Create sqlite databases
  file:
    name: "{{ sqlite_dir }}/{{ item }}"
    state: file
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0644
  with_items: "{{ sqlite_dbs }}"
