---
# tasks file for sqlite

# Setup/install tasks
- name: Ensure SQLite packages are installed
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ sqlite_packages | list }}"
  when: sqlite_packages | length
