---
# bash shell tasks

# Bash Prompt
- name: Copy custom bash prompt
  copy:
    src: "bash_prompt.sh"
    dest: "{{ shell_home }}/.bash_prompt"
    mode: 0644
    owner: "{{ shell_user }}"
    group: "{{ shell_user }}"

- name: Source custom bash prompt
  blockinfile:
    path: "{{ shell_home }}/.bashrc"
    marker: "# {mark} Prompt configuration."
    block: |
      if [ -f ~/.bash_prompt ]; then
          . ~/.bash_prompt
      fi

# Bash Path
- name: Copy custom bash path
  copy:
    src: "bash_path.sh"
    dest: "{{ shell_home }}/.bash_path"
    mode: 0644
    owner: "{{ shell_user }}"
    group: "{{ shell_user }}"

- name: Source custom bash path
  blockinfile:
    path: "{{ shell_home }}/.bashrc"
    marker: "# {mark} Path configuration."
    block: |
      if [ -f ~/.bash_path ]; then
          . ~/.bash_path
      fi

# Bash Aliases
- name: Copy custom bash aliases
  copy:
    src: "bash_aliases.sh"
    dest: "{{ shell_home }}/.bash_aliases"
    mode: 0644
    owner: "{{ shell_user }}"
    group: "{{ shell_user }}"
