---
# tasks file for mongodb

- name: Install PIP
  apt:
    package: python-pip
    state: present

- name: Install PyMongo
  pip:
    name: pymongo
    state: present
    executable: pip2

# - name: Add repository key
#   apt_key:
#     id: EA312927
#     url: "http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xEA312927"
#     state: present

# - name: Add mongodb apt source
#   apt_repository:
#     repo: "deb http://repo.mongodb.org/apt/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }}/mongodb-org/3.2 {{ mongodb_repository_section }}"
#     state: present
#     filename: mongodb-org-3.2

- name: Get MongoDB Key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
    state: present
  become: yes

- name: Install MongoDB repository
  lineinfile:
    dest: /etc/apt/sources.list.d/mongodb-org-3.6.list
    line: "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/3.6 multiverse"
  register: mongodb_repo

# - name: Get MongoDB Key
#   apt_key:
#     keyserver: keyserver.ubuntu.com
#     id: 0C49F3730359A14518585931BC711F9BA15703C6

# - name: Install MongoDB repository
#   lineinfile:
#     dest: /etc/apt/sources.list
#     line: "deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/3.4 multiverse"
#   register: mongodb_repo

- name: Updating apt cache
  apt:
    update_cache: yes
  when: mongodb_repo.changed

- name: Install MongoDb
  apt:
    name: "{{ item }}"
    state: present
    force: yes
    install_recommends: yes
  with_items:
    # - mongodb-org-server
    - mongodb-org

- name: Copy mongod template for Xenial
  template:
    src: "mongod.service.{{ ansible_distribution_release }}.j2"
    dest: "/etc/systemd/system/mongod.service"
    owner: root
    group: root
    mode: 0644

- name: Ensure mongodb is started and set to run on startup
  service:
    name: mongod
    state: started
    enabled: yes
