---
# defaults file for mysql

mysql_root_username: root
mysql_root_password: secret

mysql_daemon: mysql

mysql_packages:
  - mysql-common
  - mysql-server
  - mytop

mysql_bind_address: 127.0.0.1

# Databases.
mysql_databases:
  - name: homestead
    collation: utf8mb4_bin
    encoding: UTF8mb4
#   - name: example
#     collation: utf8_general_ci
#     encoding: utf8
#     replicate: 1

# Users.
mysql_users:
  - name: homestead
    password: secret
    priv: "*.*:ALL,GRANT"
#   - name: example
#     host: 127.0.0.1
#     password: secret
#     priv: *.*:USAGE
