---
# defaults file for mysql

# Default mysql user.
mysql_user: "{{ config_user | default(ansible_env.SUDO_USER) }}"

# Default mysql home.
mysql_home: "{{ config_home | default(ansible_env.HOME) }}"

# Build dependencies for packages (will be installed with apt).
mysql_packages:
  - mysql-common
  - mysql-server
  - mysql-client
  - python-mysqldb
  - libmysqlclient-dev
  - mytop

# MySQL connection settings
mysql_conf: /etc/mysql/mysql.conf.d/mysqld.cnf
# mysql_conf: /etc/mysql/my.cnf
mysql_bind_address: '0.0.0.0'
mysql_port: "3306"

# The default root user installed by mysql - almost always root
mysql_root_home: /root
mysql_root_username: root
mysql_root_password: root

# Databases
mysql_databases: []
#   - name: example
#     collation: utf8_general_ci
#     encoding: utf8
#     replicate: 1

# Users
mysql_users:
  - name: homestead
    host: "%"
    password: secret
    priv: "*.*:ALL,GRANT"

# Adminer
# adminer_install_dir: /opt/adminer
adminer_install_dir: /usr/share/adminer
adminer_install_filename: adminer.php
adminer_symlink_dirs:
  - /usr/share/adminer/index.php
