---
# defaults file for mysql

mysql_packages:
  - mysql-common
  - mysql-server
  - mysql-client
  - python-mysqldb
  - libmysqlclient-dev
  - mytop

# The default root user installed by mysql - almost always root
mysql_root_home: /root
mysql_root_username: root
mysql_root_password: root

# MySQL Databases
mysql_databases: []
#   - name: example
#     collation: utf8_general_ci
#     encoding: utf8
#     replicate: 1

# MySQL Users
mysql_users: []
#   - name: example
#     host: 127.0.0.1
#     password: secret
#     priv: *.*:USAGE
