---
# tasks file for apache

# Apache installation
- name: Ensure Apache is installed.
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ apache_packages | list }}"

# Apache configuration
- name: Add servername to apache config
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '^(.*)ServerName(.*)$'
    line: "ServerName localhost"
    owner: root
    group: root
    mode: 0644
  notify: Restart Apache

- name: Edit apache directory config
  lineinfile:
    path: /etc/apache2/mods-available/dir.conf
    regexp: '^(.*)DirectoryIndex(.*)$'
    line: DirectoryIndex index.php index.html index.cgi index.pl index.xhtml index.htm
    state: present
  notify: Restart Apache

- name: Configure Apache2 user and group
  lineinfile:
    dest: /etc/apache2/envvars
    regexp: "^export {{ item.param }}="
    line: "export {{ item.param }}={{ item.value }}"
  with_items :
    - { param: APACHE_RUN_USER, value: "{{ apache_user }}" }
    - { param: APACHE_RUN_GROUP, value: "{{ apache_user }}" }

# Apache modules
- name: Enable Apache modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items: "{{ apache_modules }}"
  notify: Restart Apache

# Apache vHosts
- name: Remove default Apache2 vhosts
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: Restart Apache

- name: Remove default Apache2 ssl vhosts
  file:
    path: /etc/apache2/sites-enabled/default-ssl.conf
    state: absent
  notify: Restart Apache

# Apache service
- name: Ensure Apache has selected state and enabled on boot.
  service:
    name: "{{ apache_service }}"
    state: "{{ apache_state }}"
    enabled: "{{ apache_enabled }}"
