---
# tasks file for apache

# Install Apache
- name: Ensure Apache is installed
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ apache_packages | list }}"

# Configure Apache
- name: Add servername to Apache config
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '^(.*)ServerName(.*)$'
    line: "ServerName {{ ansible_hostname }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache

- name: Edit apache directory config
  lineinfile:
    path: /etc/apache2/mods-available/dir.conf
    regexp: '^(.*)DirectoryIndex(.*)$'
    line: DirectoryIndex index.php index.html index.cgi index.pl index.xhtml index.htm
    state: present
  notify: restart apache

- name: Set nicer permissions on Apache log directory
  file:
    path: "/var/log/{{ apache_service }}"
    state: directory
    mode: 0755
    recurse: true

# Apache mod support
- name: Enable Apache mods
  file:
    src: "/etc/apache2/mods-available/{{ item }}"
    dest: "/etc/apache2/mods-enabled/{{ item }}"
    state: link
  with_items: "{{ apache_mods_enabled }}"
  notify: restart apache

- name: Disable Apache mods
  file:
    path: "/etc/apache2/mods-enabled/{{ item }}"
    state: absent
  with_items: "{{ apache_mods_disabled }}"
  notify: restart apache

# Apache vhosts
- name: Add apache vhosts configuration
  template:
    src: vhosts.conf.j2
    dest: "/etc/apache2/sites-available/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts

- name: Add vhost symlink in sites-enabled
  file:
    src: "/etc/apache2/sites-available/{{ apache_vhosts_filename }}"
    dest: "/etc/apache2/sites-enabled/{{ apache_vhosts_filename }}"
    state: link
  notify: restart apache
  when: apache_create_vhosts

- name: Remove default vhost in sites-enabled
  file:
    path: "/etc/apache2/sites-enabled/{{ apache_default_vhost_filename }}"
    state: absent
  notify: restart apache
  when: apache_remove_default_vhost

# Enable Apache
- name: Ensure Apache has selected state and enabled on boot
  service:
    name: "{{ apache_service }}"
    state: "{{ apache_state }}"
    enabled: yes
