---
- name: Desktop Playbook
  hosts: all

  vars_files:
    - vars/config.yml

  pre_tasks:

    - name: Run configured pre-provision shell scripts
      script: "{{ item }}"
      with_items: "{{ config_pre_provision_scripts | default([]) }}"
      when: config_pre_provision_scripts | length

    - name: Include optional configuration files
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/vault.yml"
        - "{{ playbook_dir }}/vars/vault.yml"
        - "{{ playbook_dir }}/vars/secrets.yml"
        - "{{ playbook_dir }}/secrets.yml"
        - "{{ playbook_dir }}/local.config.yml"

    - name: Upgrade packages
      become: yes
      apt:
        upgrade: safe
        update_cache: yes
        cache_valid_time: 300

  roles:

    # Base roles
    - { role: common,      tags: ['base'] }
    - { role: admin,       tags: ['base'] }
    - { role: ssh,         tags: ['base'] }
    - { role: git,         tags: ['base'] }
    - { role: shell,       tags: ['base'] }

    # Language roles
    - { role: python,      tags: ['languages'] }
    - { role: ruby,        tags: ['languages'] }
    - { role: node,        tags: ['languages'] }

    # Browser roles
    - { role: chromium,    tags: ['browser'] }
    - { role: firefox,     tags: ['browser'] }

    # Editor roles
    - { role: sublime,     tags: ['editor'] }

    # Desktop roles
    - { role: desktop,     tags: ['desktop'] }
    - { role: themes,      tags: ['desktop'] }
    - { role: fonts,       tags: ['desktop'] }
    - { role: xfce,        tags: ['desktop'] }
    - { role: apps,        tags: ['desktop'] }

    # Virtualization roles
    # - { role: docker,      tags: ['virtualization'] }
    # - { role: vagrant,     tags: ['virtualization'] }

    # Server roles
    - { role: mysql,      tags: ['server'] }
    - { role: sqlite,     tags: ['server'] }
    - { role: php,        tags: ['server'] }
    - { role: composer,   tags: ['server'] }

  tasks:

    - name: Run configured post-provision shell scripts
      script: "{{ item }}"
      with_items: "{{ config_post_provision_scripts | default([]) }}"
      when: config_post_provision_scripts | length

    - name: Cleanup installation
      become: yes
      apt:
        autoclean: yes
        autoremove: yes
        update_cache: yes
        cache_valid_time: 3600
