---
- name: Desktop Playbook
  hosts: all

  vars_files:
    - vars/config.yml

  pre_tasks:

    - name: Run configured pre-provision shell scripts
      script: "{{ item }}"
      with_items: "{{ master_pre_provision_scripts | default([]) }}"
      when: master_pre_provision_scripts | length

    - name: Include optional configuration files
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/vars/vault.yml"

    - name: Upgrade packages
      become: yes
      apt:
        upgrade: safe
        update_cache: yes
        cache_valid_time: 300

  roles:

    # Base roles
    - { role: common,      tags: ['base'] }
    - { role: admin,       tags: ['base'] }
    - { role: ssh,         tags: ['base'] }
    - { role: git,         tags: ['base'] }
    - { role: desktop,     tags: ['base'] }

    # Shell roles
    - { role: bash, when: master_shell == 'bash', tags: ['shell'] }
    - { role: zsh,  when: master_shell == 'zsh',  tags: ['shell'] }

    # Language roles
    - { role: python,      tags: ['languages'] }
    - { role: ruby,        tags: ['languages'] }
    - { role: node,        tags: ['languages'] }

    # Browser roles
    - { role: chromium,    tags: ['browser'] }
    - { role: firefox,     tags: ['browser'] }

    # Editor roles
    - { role: sublime,     tags: ['editor'] }
    # - { role: atom,        tags: ['editor'] }
    # - { role: vscode,      tags: ['editor'] }

    # Theme roles
    - { role: themes,      tags: ['theme'] }
    - { role: xfce,        tags: ['theme'] }

    # App roles
    # - { role: albert,    when: '"albert" in master_installed_apps',    tags: ['app'] }
    # - { role: audacity,    when: '"audacity" in master_installed_apps',    tags: ['app'] }
    # - { role: bleachbit,    when: '"bleachbit" in master_installed_apps',    tags: ['app'] }
    # - { role: blender,    when: '"blender" in master_installed_apps',    tags: ['app'] }
    # - { role: cherrytree, when: '"cherrytree" in master_installed_apps', tags: ['app'] }
    # - { role: dbeaver, when: '"dbeaver" in master_installed_apps', tags: ['app'] }
    # - { role: filezilla,    when: '"filezilla" in master_installed_apps',    tags: ['app'] }
    # - { role: gimp, when: '"gimp" in master_installed_apps', tags: ['app'] }
    # - { role: inkscape, when: '"inkscape" in master_installed_apps', tags: ['app'] }
    # - { role: keepass, when: '"keepass" in master_installed_apps', tags: ['app'] }
    # - { role: libreoffice, when: '"libreoffice" in master_installed_apps', tags: ['app'] }
    # - { role: minecraft,    when: '"minecraft" in master_installed_apps',    tags: ['app'] }
    # - { role: notepadqq,    when: '"notepadqq" in master_installed_apps',    tags: ['app'] }
    # - { role: obs,    when: '"obs" in master_installed_apps',    tags: ['app'] }
    # - { role: remmina, when: '"remmina" in master_installed_apps', tags: ['app'] }
    # - { role: tor, when: '"tor" in master_installed_apps', tags: ['app'] }
    # - { role: transmission, when: '"transmission" in master_installed_apps', tags: ['app'] }

    # Virtualization roles
    # - { role: docker,      tags: ['virtualization'] }
    # - { role: vagrant,     tags: ['virtualization'] }

    # Server roles
    # - { role: mysql,      tags: ['server'] }
    # - { role: php,        tags: ['server'] }
    # - { role: composer,   tags: ['server'] }

    # Extra roles
    # - { role: dotfiles, when: master_dotfiles_enabled,    tags: ['extras'] }
    # - { role: security, when: master_security_enabled, tags: ['extras'] }

  tasks:

    - name: Run configured post-provision shell scripts
      script: "{{ item }}"
      with_items: "{{ master_post_provision_scripts | default([]) }}"
      when: master_post_provision_scripts | length

    - name: Cleanup installation
      become: yes
      apt:
        autoclean: yes
        autoremove: yes
        update_cache: yes
        cache_valid_time: 3600
