---
# tasks file for desktop

# Install Dependencies
- name: Install desktop dependencies
  apt:
    name: "{{ item }}"
    state: "{{ desktop_apt_state }}"
  with_items: "{{ desktop_apt_dependencies | list }}"

# Install Packages
- name: Add desktop PPA repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ desktop_apt_ppa }}"
  register: desktop_add_apt_repo

- name: Install desktop software packages
  apt:
    name: "{{ item }}"
    state: "{{ desktop_apt_state }}"
  with_items: "{{ desktop_apt_packages | list }}"
  when: desktop_add_apt_repo | succeeded

# Create Directories
- name: Make sure /usr/local/share/applications exists
  file:
    path: /usr/local/share/applications
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: Make sure startup application directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/autostart"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

# Set Permissions
- name: Set jack.sh with proper permissions
  file:
    dest: /etc/acpi/jack.sh
    owner: root
    group: root
    mode: 0755

# Imagemagick Configuration
- name: Copy imagemagick desktop entry files
  copy:
    src: "{{ item }}"
    dest: "/usr/local/share/applications/{{ item }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  with_items:
    - display-im6.q16.desktop
    - display-im6.desktop
