---
# tasks file for desktop

# Install Dependencies
- name: Install desktop dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ desktop_apt_dependencies | list }}"
  when: desktop_apt_dependencies | length

# Install PPA Packages
- name: Add desktop PPA repositories
  apt_repository:
    repo: "{{ item.ppa }}"
    state: present
  with_items: "{{ desktop_apt_ppa }}"
  when: desktop_apt_ppa | length

- name: Install desktop PPA packages
  apt:
    name: "{{ item.pkg }}"
    state: present
  with_items: "{{ desktop_apt_ppa }}"
  when: desktop_apt_ppa | length

# Install Desktop Packages
- name: Install desktop software packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ desktop_apt_packages | list }}"
  when: desktop_apt_packages | length

# Create Directories
- name: Make sure /usr/local/share/applications exists
  file:
    path: /usr/local/share/applications
    state: directory
    owner: "{{ desktop_user }}"
    group: "{{ desktop_user }}"

- name: Make sure startup application directory exists
  file:
    path: "{{ desktop_home }}/.config/autostart"
    state: directory
    owner: "{{ desktop_user }}"
    group: "{{ desktop_user }}"

# Set Permissions
- name: Set jack.sh with proper permissions
  file:
    dest: /etc/acpi/jack.sh
    owner: root
    group: root
    mode: 0755
