---
# tasks file for xfce

# GTK Bookmarks
- name: Create GTK bookmarks
  lineinfile:
    path: "{{ ansible_env.HOME }}/.config/gtk-3.0/bookmarks"
    line: "{{ item }}"
    state: present
    create: yes
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  with_items:
    - "file://{{ ansible_env.HOME }}/Documents"
    - "file://{{ ansible_env.HOME }}/Downloads"
    - "file://{{ ansible_env.HOME }}/Public"

# GTK File Chooser
- name: Configure GTK file chooser
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.config/gtk-2.0/gtkfilechooser.ini"
    regexp: "{{ item.param }}"
    line: "{{ item.value }}"
    state: present
    create: yes
  with_items :
    - { param: "StartupMode=", value: "StartupMode=cwd" }
    - { param: "DefaultFolder=", value: "DefaultFolder=cwd" }

# Profile Image
- name: Copy profile face
  copy:
    src: face
    dest: "{{ ansible_env.HOME }}/.face"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0664

# XFCE panel
- name: Clean panel config directory
  file:
    path: "{{ ansible_env.HOME }}/.config/xfce4/panel"
    state: absent

- name: Create panel config directory
  file:
    path: "{{ ansible_env.HOME }}/.config/xfce4/panel"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

# Weather icons
- name: Clone weather icons
  git:
    repo: https://github.com/kevlar1818/xfce4-weather-mono-icons
    dest: "{{ ansible_env.HOME }}/.cache/xfce4-weather-mono-icons"
  register: xfce_weather_icons_git

- name: Copy weather icons
  copy:
    src: "{{ ansible_env.HOME }}/.cache/xfce4-weather-mono-icons/{{ item }}"
    dest: /usr/share/xfce4/weather/icons
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  with_items:
    - WSky-Light
    - WSky
  when: xfce_weather_icons_git.changed

- name: Copy weather preferences file
  copy:
    src: weather.rc
    dest: "{{ ansible_env.HOME }}/.config/xfce4/panel/weather-13.rc"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

# Whiskermenu
- name: Copy menu icon
  copy:
    src: ubuntu-logo-menu.png
    dest: /usr/share/pixmaps/ubuntu-logo-menu.png

- name: Copy whiskermenu preferences file
  copy:
    src: whiskermenu.rc
    dest: "{{ ansible_env.HOME }}/.config/xfce4/panel/whiskermenu-7.rc"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

# XFCE Panel launchers
- name: Create panel launcher directories
  file:
    path: "{{ ansible_env.HOME }}/.config/xfce4/panel/{{ item }}"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  with_items:
    - launcher-1
    - launcher-2
    - launcher-9
    - launcher-12

- name: Copy chromium launcher file
  copy:
    src: chromium.desktop
    dest: "{{ ansible_env.HOME }}/.config/xfce4/panel/launcher-1/chromium.desktop"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: Copy thunar launcher file
  copy:
    src: thunar.desktop
    dest: "{{ ansible_env.HOME }}/.config/xfce4/panel/launcher-2/thunar.desktop"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: Copy sublime launcher file
  copy:
    src: sublime.desktop
    dest: "{{ ansible_env.HOME }}/.config/xfce4/panel/launcher-9/sublime.desktop"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: Copy terminal launcher file
  copy:
    src: terminal.desktop
    dest: "{{ ansible_env.HOME }}/.config/xfce4/panel/launcher-12/terminal.desktop"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

# Xfconf Settings
- name: Setup Thunar
  shell: "{{ item }}"
  become: true
  become_user: "{{ ansible_env.USER }}"
  with_items:
    - xfconf-query -c thunar -p /last-view -n -t string -s ThunarIconView
    - xfconf-query -c thunar -p /last-icon-view-zoom-level -n -t string -s THUNAR_ZOOM_LEVEL_NORMAL
    - xfconf-query -c thunar -p /last-separator-position -n -t int -s 170
    - xfconf-query -c thunar -p /last-show-hidden -n -t bool -s true
    - xfconf-query -c thunar -p /misc-single-click -n -t bool -s false
    - xfconf-query -c thunar -p /hidden-bookmarks -n -a -t string -s "network:///"

- name: Setup Panel plugins
  shell: "{{ item }}"
  become: true
  become_user: "{{ ansible_env.USER }}"
  with_items:
    - xfconf-query -c xfce4-panel -p /panels/panel-1/plugin-ids -n -a -t int -s 7 -t int -s 2 -t int -s 12 -t int -s 1 -t int -s 9 -t int -s 3 -t int -s 15 -t int -s 4 -t int -s 11 -t int -s 6 -t int -s 13 -t int -s 8 -t int -s 5
    - xfconf-query -c xfce4-panel -p /plugins/plugin-3 -n -t string -s tasklist
    - xfconf-query -c xfce4-panel -p /plugins/plugin-3/flat-buttons -n -t bool -s true
    - xfconf-query -c xfce4-panel -p /plugins/plugin-3/window-scrolling -n -t bool -s false
    - xfconf-query -c xfce4-panel -p /plugins/plugin-3/show-handle -n -t bool -s true
    - xfconf-query -c xfce4-panel -p /plugins/plugin-15 -n -t string -s separator
    - xfconf-query -c xfce4-panel -p /plugins/plugin-15/expand -n -t bool -s true
    - xfconf-query -c xfce4-panel -p /plugins/plugin-15/style -n -t uint -s 0
    - xfconf-query -c xfce4-panel -p /plugins/plugin-4 -n -t string -s pager
    - xfconf-query -c xfce4-panel -p /plugins/plugin-4/rows -n -t uint -s 1
    - xfconf-query -c xfce4-panel -p /plugins/plugin-4/workspace-scrolling -n -t bool -s false
    - xfconf-query -c xfce4-panel -p /plugins/plugin-5 -n -t string -s clock
    - xfconf-query -c xfce4-panel -p /plugins/plugin-5/digital-format -n -t string -s "%I:%M %p"
    - xfconf-query -c xfce4-panel -p /plugins/plugin-5/timezone -n -t string -s "America/New_York"
    - xfconf-query -c xfce4-panel -p /plugins/plugin-6 -n -t string -s systray
    - xfconf-query -c xfce4-panel -p /plugins/plugin-6/show-frame -n -t bool -s false
    - xfconf-query -c xfce4-panel -p /plugins/plugin-6/size-max -n -t uint -s 26
    - xfconf-query -c xfce4-panel -p /plugins/plugin-7 -n -t string -s whiskermenu
    - xfconf-query -c xfce4-panel -p /plugins/plugin-8 -n -t string -s power-manager-plugin
    - xfconf-query -c xfce4-panel -p /plugins/plugin-11 -n -t string -s separator
    - xfconf-query -c xfce4-panel -p /plugins/plugin-11/style -n -t uint -s 0
    - xfconf-query -c xfce4-panel -p /plugins/plugin-1 -n -t string -s launcher
    - xfconf-query -c xfce4-panel -p /plugins/plugin-1/items -n -a -t string -s chromium.desktop
    - xfconf-query -c xfce4-panel -p /plugins/plugin-2 -n -t string -s launcher
    - xfconf-query -c xfce4-panel -p /plugins/plugin-2/items -n -a -t string -s thunar.desktop
    - xfconf-query -c xfce4-panel -p /plugins/plugin-12 -n -t string -s launcher
    - xfconf-query -c xfce4-panel -p /plugins/plugin-12/items -n -a -t string -s terminal.desktop
    - xfconf-query -c xfce4-panel -p /plugins/plugin-9 -n -t string -s launcher
    - xfconf-query -c xfce4-panel -p /plugins/plugin-9/items -n -a -t string -s sublime.desktop
    - xfconf-query -c xfce4-panel -p /plugins/plugin-13 -n -t string -s weather

- name: Set Power Manager
  shell: "{{ item }}"
  become: true
  become_user: "{{ ansible_env.USER }}"
  with_items:
    - xfconf-query -c xfce4-power-manager -p /show-tray-icon -n -t int -s 0

- name: Set XFCE Session
  shell: "{{ item }}"
  become: true
  become_user: "{{ ansible_env.USER }}"
  with_items:
    - xfconf-query -c xfce4-session -p /compat/LaunchGNOME -n -t bool -s true

- name: Restart xfce4 panel
  shell: xfce4-panel --restart
  become: true
  become_user: "{{ ansible_env.USER }}"
