---
# defaults file for composer

# Default composer user.
composer_user: "{{ config_user | default(ansible_env.SUDO_USER) }}"

# Default composer group.
composer_group: "{{ composer_user }}"

# Default composer home.
composer_home: "{{ config_home | default(ansible_env.HOME) }}"

# The path where composer will be installed and available to your system. Should be in your user's `$PATH` so you can run commands simply with `composer` instead of the full path.
composer_path: /usr/local/bin/composer

# Runs composer self-update.
composer_keep_updated: false

# The directory where global packages will be installed.
# composer_home_path: "{{ composer_home }}/.composer"
composer_home_path: '~/.composer'

# A list of packages to install globally. See commented examples below for
# usage; the 'release' is optional, and defaults to '@stable'.
composer_global_packages:
  - { name: laravel/envoy }
  - { name: laravel/installer }
  - { name: cpriego/valet-linux }

# Directory to park valet sites
composer_park: "{{ composer_home }}/Public"
