---
# defaults file for composer

# The path where composer will be installed and available to your system. Should be in your user's `$PATH` so you can run commands simply with `composer` instead of the full path.
composer_path: /usr/local/bin/composer

# The directory where global packages will be installed.
composer_home_path: "{{ ansible_env.HOME }}/.composer"
composer_home_owner: "{{ ansible_env.USER }}"
composer_home_group: "{{ ansible_env.USER }}"

# If `true`, and if there are any configured `composer_packages`, the `vendor/bin` directory inside `composer_home_path` will be added to the system's default `$PATH` (for all users).
composer_add_to_path: true

# A list of packages to install globally. See commented examples below for
# usage; the 'release' is optional, and defaults to '@stable'.
composer_packages:
  - { name: laravel/envoy, release: "~1.0" }
  - { name: laravel/installer, release: "~1.1" }
  - { name: hirak/prestissimo, release: "^0.3" }
  - { name: phpunit/phpunit, release: "@stable" }
  - { name: phpunit/dbunit, release: "@stable" }
  - { name: phploc/phploc, release: "@stable" }
  - { name: phpmd/phpmd, release: "@stable" }
  - { name: sebastian/phpcpd, release: "@stable" }
  - { name: tightenco/jigsaw, release: "@stable" }
  - { name: codeception/codeception, release: "@stable" }
  - { name: friendsofphp/php-cs-fixer, release: "@stable" }
  - { name: squizlabs/php_codesniffer, release: "@stable" }
