---
# defaults file for composer

composer_path: /usr/local/bin/composer
composer_keep_updated: false
composer_version: ''

# The directory where global packages will be installed.
composer_home_path: "{{ ansible_env.HOME }}/.composer"
composer_home_owner: "{{ ansible_env.USER }}"
composer_home_group: "{{ ansible_env.USER }}"

# A list of packages to install globally. See commented examples below for
# usage; the 'release' is optional, and defaults to '@stable'.
composer_global_packages:
  - { name: laravel/envoy, release: "~1.0" }
  - { name: laravel/installer, release: "~1.1" }
  - { name: hirak/prestissimo, release: '^0.3' }
  - { name: phpunit/dbunit, release: "@stable" }
  - { name: phploc/phploc, release: "@stable" }
  - { name: squizlabs/php_codesniffer, release: "@stable" }

composer_add_to_path: true

# Add a project vendor/bin directory to the PATH
composer_add_project_to_path: false
#composer_project_path: /path/to/project/vendor/bin
