---
# defaults file for sublime

# Array of sublime apt package dependencies.
sublime_dependencies:
  - apt-transport-https

# Default sublime user.
sublime_user: "{{ ansible_env.USER }}"

# Default sublime home.
sublime_home: "{{ ansible_env.HOME }}"

# Sublime text gpg url.
sublime_gpg_key: https://download.sublimetext.com/sublimehq-pub.gpg

# Sublime apt key.
sublime_apt_key: ADAE6AD28A8F901A

# Sublime text repo channel. Options are `stable` or `dev`.
sublime_repo_channel: stable

# Sublime text configuration directory.
sublime_config_dir: "{{ sublime_home }}/.config/sublime-text-3"

# Sublime text installed packages directory.
sublime_installed_pkgs_dir: "{{ sublime_config_dir }}/Installed Packages"

# Sublime text user packages and preferences directory.
sublime_user_preferences_dir: "{{ sublime_config_dir }}/Packages/User"

# Sublime text local license directory.
sublime_local_license_dir: "{{ sublime_config_dir }}/Local"

# URL to install Sublime Package Control.
sublime_package_control_url: "https://packagecontrol.io/Package%20Control.sublime-package"

# Whether to backup package control preferences.
sublime_package_control_backup: yes

# Array of packages to install via packagecontrol.io.
sublime_packages:
  - "A File Icon"
  - "AlignTab"
  - "BracketHighlighter"
  - "Color Highlighter"
  - "DocBlockr"
  - "EditorConfig"
  - "GitGutter"
  - "HyperClick"
  - "Jinja2"
  - "Laravel 5 Artisan"
  - "Laravel 5 Snippets"
  - "Laravel Blade Highlighter"
  - "LESS"
  - "Material Theme"
  - "Nodejs"
  - "Nunjucks Syntax"
  - "Package Control"
  - "SCSS"
  - "SideBarEnhancements"
  - "TodoReview"
  - "Vue Syntax Highlight"
  - "Dockerfile Syntax Highlighting"
  - "RegReplace"
  - "SublimeCodeIntel"
  - "SublimeLinter"

# Array of Github repositories to install.
sublime_git_repos: []

# sublime_plugin_prefs:
#   - "AlignTab.sublime-settings"
#   # - "AlignTab/Context.sublime-menu"
#   - "ColorHighlighter.sublime-settings"
#   - "Side Bar.sublime-settings"
#   - "hyper_click.sublime-settings"
