---
# vars file for chromium

# Chromium configuration paths.
chromium_config: "{{ chromium_home }}/.config/chromium/Default"
chromium_preferences: "{{ chromium_config }}/Preferences"
chromium_extensions_dir: /usr/share/chromium-browser/extensions

# Array of chromium apt packages to install.
chromium_packages:
  - chromium-browser
  - chromium-browser-l10n
  - chromium-codecs-ffmpeg-extra
  - upower
  - opus-tools
  - speex

# Default chromium filename.
chromium_policies_filename: user-policy.json
