---
# defaults file for docker

# Default docker user.
docker_user: "{{ config_user | default(ansible_env.SUDO_USER) }}"

# Default docker home.
docker_home: "{{ config_home | default(ansible_env.HOME) }}"
