---
# tasks file for couchdb

- name: Adding CouchDB APT repository key
  become: yes
  apt_key:
    url: https://couchdb.apache.org/repo/bintray-pubkey.asc
    state: present

- name: Add CouchDB official APT repository
  become: yes
  apt_repository:
    repo: "deb https://apache.bintray.com/couchdb-deb {{ ansible_distribution_release }} main"

- name: Ensure CouchDB packages are installed
  become: yes
  apt:
    name: couchdb
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Copy CouchDB configuration
  template:
    src: settings.ini.j2
    dest: "{{ couchdb_local_conf_path }}/settings.ini"
    owner: couchdb
    group: couchdb
    mode: 0644
  notify: restart couchdb

- name: Ensure CouchDB is started and enabled to start at boot
  service:
    name: couchdb
    state: started
    enabled: yes
