---
# tasks file for vagrant

# Install Virtualbox
- name: Configure the Oracle APT key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox.asc
    state: present

- name: Configure the VirtualBox APT repositories
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state: present

- name: Install VirtualBox
  apt:
    name: "virtualbox-{{ virtualbox_version }}"
    state: present

# Install Vargrant
- name: Check if Vagrant is installed
  command: dpkg-query -W vagrant
  register: vagrant_check_deb
  failed_when: vagrant_check_deb.rc > 1
  changed_when: vagrant_check_deb.rc == 1

- name: Download Vagrant
  get_url:
    url: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.deb"
    dest: "/tmp/download-vagrant-latest.deb"
  when: vagrant_check_deb.rc == 1

- name: Install Vagrant
  apt:
    deb: "/tmp/download-vagrant-latest.deb"
  when: vagrant_check_deb.rc == 1

- name: Clean Vagrant deb file
  file:
    path: /tmp/download-vagrant-latest.deb
    state: absent
