---
# tasks file for vagrant

# Install Virtualbox
# ID: curl https://www.virtualbox.org/download/oracle_vbox_2016.asc | gpg --list-packets
- name: Configure the Oracle APT key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    id: A2F683C52980AECF
    state: present

- name: Configure the VirtualBox APT repositories
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state: present

- name: Install VirtualBox
  apt:
    name: "virtualbox-{{ virtualbox_version }}"
    state: present

- name: Install VirtualBox shared packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ virtualbox_shared_packages | list }}"

- name: Ensure virtualbox group is present
  group:
    name: vboxusers
    state: present
    system: yes

- name: Set username
  command: whoami
  register: virtualbox_username
  check_mode: no
  changed_when: False

- name: Ensure user is added to vboxusers group
  become: yes
  user:
    name: "{{ virtualbox_username.stdout }}"
    groups: vboxusers
    append: yes

# Install Vargrant
- name: Check if Vagrant is installed
  command: dpkg-query -W vagrant
  register: vagrant_check_deb
  failed_when: vagrant_check_deb.rc > 1
  changed_when: vagrant_check_deb.rc == 1

- name: Download Vagrant
  get_url:
    url: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.deb"
    dest: "/tmp/download-vagrant-latest.deb"
  when: vagrant_check_deb.rc == 1

- name: Install Vagrant
  apt:
    deb: "/tmp/download-vagrant-latest.deb"
  when: vagrant_check_deb.rc == 1

- name: Clean Vagrant deb file
  file:
    path: /tmp/download-vagrant-latest.deb
    state: absent
