---
# tasks file for dotfiles

- name: Check that the user SSH key exists
  stat:
    path: "{{ dotfiles_ssh_key }}"
  register: dotfiles_ssh_key_exists

- name: Clone dotfiles repository
  become: true
  become_user: "{{ dotfiles_user }}"
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_home }}/{{ dotfiles_path }}"
    update: no
    bare: yes
    key_file: "{{ dotfiles_ssh_key }}"
    accept_hostkey: yes
  when: dotfiles_ssh_key_exists.stat.exists == true

- name: Ensure dotfiles directory exists
  stat:
    path: "{{ dotfiles_home }}/{{ dotfiles_path }}"
  register: dotfiles_created
  # when: dotfiles_created.stat.isdir is defined and dotfiles_created.stat.isdir

- name: Checkout dotfiles
  become: true
  become_user: "{{ dotfiles_user }}"
  shell: "/usr/bin/git --git-dir=$HOME/{{ dotfiles_path }}/ --work-tree=$HOME checkout -f"
  args:
    chdir: "{{ dotfiles_home }}"
  when: dotfiles_created.stat.exists

- name: Config dotfiles repo
  become: true
  become_user: "{{ dotfiles_user }}"
  shell: "/usr/bin/git --git-dir=$HOME/{{ dotfiles_path }}/ --work-tree=$HOME config --local status.showUntrackedFiles no"
  args:
    chdir: "{{ dotfiles_home }}"
  when: dotfiles_created.stat.exists
