---
# tasks file for vscode

# Install via FWlink

# - name: Check if visual studio code is installed
#   command: dpkg-query -W visual-studio-code
#   register: vscode_check_deb
#   become: yes
#   failed_when: vscode_check_deb.rc > 1
#   changed_when: vscode_check_deb.rc == 1

# - name: Download and install visual studio code
#   apt:
#     deb: https://go.microsoft.com/fwlink/?LinkID=760868
#   when: vscode_check_deb.rc == 1

# Install via Apt Repo

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Install Microsoft GPG key
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present

- name: Add Microsoft Visual Studio Code Repository
  apt_repository:
    repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
    filename: vscode
    state: present
    update_cache: yes

- name: Install Visual Studio Code including dependencies
  apt:
    name: "{{ item }}"
    update_cache: true
  with_items:
    - libgtk2.0-0
    - libxss1
    - libasound2
    - code

# Install via Redis URL

# - name: create download directory
#   file:
#     state: directory
#     mode: 'u=rwx,go=rx'
#     dest: "{{ visual_studio_code_download_dir }}"

# - name: ensure ca-certificates installed
#   become: yes
#   apt:
#     name: ca-certificates
#     state: present

# - name: download Visual Studio Code
#   get_url:
#     url: "{{ visual_studio_code_redis_url }}"
#     dest: "{{ visual_studio_code_download_dir }}/{{ visual_studio_code_redis_filename }}"
#     sha256sum: "{{ visual_studio_code_redis_sha256sum }}"
#     force: no
#     use_proxy: yes
#     validate_certs: yes
#     mode: 'u=rw,go=r'

# - name: install Visual Studio Code
#   become: yes
#   apt:
#     deb: "{{ visual_studio_code_download_dir }}/{{ visual_studio_code_redis_filename }}"

# Install vscode Extenstions

- name: install extension cli dependencies
  # become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - gconf2
    - libasound2
    - libgtk2.0-0
    - libxss1

- name: Visual Studio Code | Get installed extensions
  command: "code --list-extensions"
  changed_when: false
  register: vscode_installed_extensions

- name: Visual Studio Code | Install extensions
  shell: "code --install-extension {{ item }} {{ vscode_extra_extension_params | default('') }}"
  with_items: "{{ vscode_extensions | default([]) }}"
  when: item not in vscode_installed_extensions.stdout_lines

# - name: Install Extensions for user(s)
#   become: yes
#   become_user: "{{ ansible_env.USER }}"
#   command: "code --user-data-dir=/tmp --install-extension '{{ item.1 }}'"
#   with_subelements:
#     - "{{ vscode_extensions }}"
#     - extensions
#     - skip_missing: yes
#   register: vscode_install_result
#   changed_when: "'already installed' not in vscode_install_result.stdout"
