---
# defaults file for shell

# Default shell type. Use either `bash` or `zsh`.
shell_type: "{{ master_shell | default('bash') }}"

# Default shell user.
shell_user: "{{ master_user | default(ansible_env.SUDO_USER) }}"

# Default shell home.
shell_home: "{{ master_home | default(ansible_env.HOME) }}"
