---
# defaults file for shell

# Default shell type. Use either `bash` or `zsh`.
shell_type: "{{ config_shell | default('bash') }}"

# Default shell user.
shell_user: "{{ config_user | default(ansible_env.SUDO_USER) }}"

# Default shell home.
shell_home: "{{ config_home | default(ansible_env.HOME) }}"
