---
# defaults file for shell

# Default shell type. Use either `bash` or `zsh`.
shell_type: "{{ mimetic_shell | default('bash') }}"

# Default shell user.
shell_user: "{{ mimetic_user | default(ansible_env.USER) }}"

# Default shell home.
shell_home: "{{ mimetic_home | default(ansible_env.HOME) }}"
