---
# defaults file for ssh

# Default ssh user.
ssh_user: "{{ master_user | default(ansible_env.SUDO_USER) }}"

# Default ssh home.
ssh_home: "{{ master_home | default(ansible_env.HOME) }}"

# Build dependencies for packages (will be installed with apt).
ssh_dependencies: []

# Default ssh public & private key files.
ssh_privkey: "{{ ssh_home }}/.ssh/id_rsa"
ssh_pubkey: "{{ ssh_home }}/.ssh/id_rsa.pub"

# SSH key parameters
ssh_generate_key: yes
ssh_key_type: rsa
ssh_key_bits: 4096
ssh_key_file: .ssh/id_rsa
ssh_key_comment: "{{ master_email | default(inventory_hostname) }}"
