---
# defaults file for admin

# Default admin user.
admin_user: "{{ master_user | default(ansible_env.SUDO_USER) }}"

# Default admin password
admin_password: "{{ master_password | default(omit) }}"

# Default admin home.
admin_home: "{{ master_home | default(ansible_env.HOME) }}"

# Default admin full name.
admin_fullname: "{{ master_name | default(ansible_user_gecos.split(',')[0]) }}"

# Default admin user group.
admin_group: "{{ admin_user }}"

# Default groups for the admin user.
admin_groups:
  - adm
  - sudo
  - cdrom
  - dip
  - plugdev
  - lpadmin
  - www-data

# XDG user directories. To remove a folder, set its value to "$HOME".
admin_xdg_directories:
  - { name: DESKTOP,     path: "$HOME/Desktop",   dir: Desktop,   state: directory }
  - { name: DOWNLOAD,    path: "$HOME/Downloads", dir: Downloads, state: directory }
  - { name: PUBLICSHARE, path: "$HOME/Public",    dir: Public,    state: directory }
  - { name: DOCUMENTS,   path: "$HOME/Documents", dir: Documents, state: directory }
  - { name: TEMPLATES,   path: "$HOME",           dir: Templates, state: absent  }
  - { name: MUSIC,       path: "$HOME",           dir: Music,     state: absent  }
  - { name: PICTURES,    path: "$HOME",           dir: Pictures,  state: absent  }
  - { name: VIDEOS,      path: "$HOME",           dir: Videos,    state: absent  }

# Home folder encryption switch.
admin_home_encryption: false

# The time (in seconds) to set the current apt cache. Current default is set for one day.
admin_apt_cache_time: "{{ master_apt_cache_time | default(86400) }}"

# Home folder encyption dependencies.
admin_encryption_dependencies:
  - ecryptfs-utils
  - cryptsetup
