---
# defaults file for apps

# Default desktop user.
app_user: "{{ master_user | default(ansible_env.SUDO_USER) }}"

# Default desktop home.
app_home: "{{ master_home | default(ansible_env.HOME) }}"

# Array of Personal Package Archives (PPAs) to add. Additional PPAs can be found at: https://launchpad.net/.
app_ppa:
  - { ppa: "ppa:inkscape.dev/stable",              pkg: inkscape }
  - { ppa: "ppa:phoerious/keepassxc",              pkg: keepassxc }
  - { ppa: "ppa:libreoffice/ppa",              pkg: libreoffice }
  - { ppa: "ppa:otto-kesselgulasch/gimp",              pkg: gimp }
  # - { ppa: "ppa:dawidd0811/neofetch",              pkg: neofetch }
  # - { ppa: "ppa:giuspen/ppa",                      pkg: cherrytree }
  # - { ppa: "ppa:serge-rider/dbeaver-ce",           pkg: dbeaver-ce }
  # - { ppa: "ppa:transmissionbt/ppa",               pkg: transmission }
  # - { ppa: "ppa:thomas-schiex/blender",            pkg: blender }
  # - { ppa: "ppa:kirillshkrogalev/ffmpeg-next",     pkg: ffmpeg }
  # - { ppa: "ppa:obsproject/obs-studio",            pkg: obs-studio }
  # - { ppa: "ppa:ubuntuhandbook1/audacity",         pkg: audacity }
  # - { ppa: "ppa:webupd8team/tor-browser",          pkg: tor-browser }
  # - { ppa: "ppa:notepadqq-team/notepadqq",         pkg: notepadqq }
  # - { ppa: "ppa:remmina-ppa-team/remmina-next",    pkg: remmina }
  # - { ppa: "ppa:remmina-ppa-team/remmina-next",    pkg: remmina-plugin-rdp }

# Array of gui desktop software packages to install
app_packages:
  - bleachbit
  - filezilla
  # - gpick
  - meld
  - mpv
  # - font-manager
  - transmission
  # - rhythmbox
