---
# tasks file for phantomjs

- name: Ensure PhantomJS native package is absent
  apt:
    name: phantomjs
    state: absent
    purge: yes

- name: Install phantomjs dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ phantomjs_dependencies }}"

- name: Check PhantomJS version
  command: "phantomjs --version"
  register: phantomjs_check
  ignore_errors: true
  failed_when: false
  changed_when: false

- name: Cleanup PhantomJS existing installation
  file:
    path: "/usr/local/bin/phantomjs"
    state: absent
  when: phantomjs_check | failed
  ignore_errors: true
  failed_when: false
  changed_when: false

- name: Download phantomjs
  unarchive:
    src: "https://github.com/Medium/phantomjs/releases/download/v{{ phantomjs_version }}/phantomjs-{{ phantomjs_version }}-linux-x86_64.tar.bz2"
    dest: "{{ phantomjs_workspace }}"
    copy: no
    creates: "{{ phantomjs_workspace }}/phantomjs-{{ phantomjs_version }}-linux-x86_64"
  when: phantomjs_check | failed

- name: Add phantomjs to local bin
  copy:
    src: "{{ phantomjs_workspace }}/phantomjs-2.1.1-linux-x86_64/bin/phantomjs"
    dest: "{{ phantomjs_bin_path }}"
    mode: 0755

- name: Copy phantomjs init script into place
  template:
    src: phantomjs.init.j2
    dest: /etc/init.d/phantomjs
    owner: root
    group: root
    mode: 0755

- name: Ensure phantomjs is enabled and will start on boot
  service:
    name: phantomjs
    state: started
    enabled: yes
  when: "{{ phantomjs_webdriver }}"

- name: Cleanup PhantomJS installer
  file:
    path: "/tmp/{{ phantomjs_workspace }}"
    state: absent
