---
# tasks file for python

# Install python
- name: Install python dependencies
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ python_dependencies | list }}"
  when: python_dependencies | length

- name: Install python APT packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ python_packages | list }}"
  when: python_packages | length

# Install pip
- name: Install python PIP packages
  become: yes
  pip:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    executable: "{{ item.executable | default(python_pip_executable) }}"
  with_items: "{{ pip_packages }}"
  when: pip_packages | length
