---

- name: Add nginx vhosts
  template:
    src: nginx/{{ item.template }}.j2
    dest: "/etc/nginx/conf.d/vhost-{{ item.vhost }}.conf"
  with_items: "{{ www_vhosts }}"
  notify: restart nginx

- name: Clean /etc/hosts file
  replace:
    dest: /etc/hosts
    regexp: '.* \# nginx vhost\n'
    replace: ''

- name: Build /etc/hosts file for tools
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item.server_name }} \# nginx vhost$'
    line: "127.0.0.1   {{ item.server_name }} {{ '#' }} nginx vhost"
    state: present
  with_items: "{{ www_nginx_vhosts }}"

- name: Build /etc/hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item.vhost }} \# nginx vhost$'
    line: "127.0.0.1   {{ item.vhost }} {{ '#' }} nginx vhost"
    state: present
  with_items: "{{ www_vhosts }}"
