---
# tasks file for mssql

- name: Set the MSSQL webserver daemon correctly when nginx is in use
  set_fact:
    mssql_webserver_daemon: nginx
  when: pbook_webserver == 'nginx'

- name: Set the MSSQL webserver daemon correctly when apache is in use
  set_fact:
    mssql_webserver_daemon: apache2
  when: pbook_webserver == 'apache'

# MSSQL Installation
- name: Add Microsoft gpg key
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present

# - name: Add Ubuntu repository
#   apt_repository:
#     repo: deb [arch=amd64] https://packages.microsoft.com/ubuntu/16.04/mssql-server xenial main
#     state: present
#   register: mssql_repo

- name: Add Ubuntu repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/config/ubuntu/16.04/prod xenial main
    state: present
    filename: mssql-release
  register: mssql_repo

- name: Update cache with repository
  apt:
    update_cache: yes
  when: mssql_repo.changed

- name: Install MSSQL Tools
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - msodbcsql
    - mssql-tools
  environment:
    ACCEPT_EULA: Y

- name: Add MSSQL tools to environment PATH
  lineinfile:
    path: /etc/environment
    line: 'PATH="$PATH:/opt/mssql-tools/bin"'

- name: Install UnixODBC
  apt:
    name: unixodbc-dev
    state: present

- name: Ensure PHP Pear is installed
  apt:
    name: php-pear
    state: present

- name: Set Pear config
  command: pear config-set php_ini `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"` system

- name: Install PECL libaries
  shell: "yes '' | pecl install {{ item }}"
  register: mssql_pecl_result
  changed_when: "mssql_pecl_result.rc == 0"
  failed_when: "not (('already installed' in mssql_pecl_result.stdout) or ('install ok:' in mssql_pecl_result.stdout))"
  with_items: "{{ mssql_pecl_extensions }}"

- name: Configure PHP-FPM extensions
  lineinfile:
    dest: /etc/php/7.1/fpm/php.ini
    regexp: "^{{ item }}"
    line: "{{ item }}"
  with_items :
    - "[mssql]"
    - "extension=sqlsrv.so"
    - "extension=pdo_sqlsrv.so"
