---
# defaults file for www

# Default www user.
www_user: "{{ ansible_env.USER }}"

# Default www home.
www_home: "{{ ansible_env.HOME }}"

# Dashboard Details
www_dashboard_install_dir: /var/www/dashboard
www_dashboard_site_title: Machina
www_dashboard_site_favicon: //cdn.rawgit.com/geerlingguy/drupalvm.github.io/master/favicon.ico

# Webserver Details
www_domain: "{{ pbook_domain | default('dashboard.dev') }}"
www_webserver: "{{ pbook_webserver | default('apache') }}"
www_apache_vhosts: "{{ apache_vhosts | default([]) }}"
www_nginx_vhosts: "{{ nginx_vhosts | default([]) }}"

# Extra Details
www_extras: "{{ pbook_extras | default([]) }}"

# Adminer Details
www_adminer_install_dir: "{{ adminer_install_dir | default('/opt/adminer') }}"
www_adminer_install_filename: "{{ adminer_install_filename | default('index.php') }}"

# Pimpmylog Details
www_pimpmylog_install_dir: "{{ pimpmylog_install_dir | default('/usr/share/php/pimpmylog') }}"

# PHP Details
www_php_version: "{{ php_version | default('N/A') }}"
www_php_memory_limit: "{{ php_memory_limit | default('N/A') }}"
www_php_enable_php_fpm: "{{ php_enable_php_fpm | default(false) }}"

# MySQL Details
www_mysql_port: "{{ mysql_port | default('3306') }}"
www_mysql_root_username: "{{ mysql_root_username | default('root') }}"
www_mysql_root_password: "{{ mysql_root_password | default('root') }}"
www_mysql_databases: "{{ mysql_databases | default([]) }}"
www_mysql_users: "{{ mysql_users | default([]) }}"

# vHosts Details
www_vhosts:
  - template: standard
    vhost: "default71.dev"
    path: "{{ ansible_env.HOME }}/Public/default-7.0"
    php: "7.1"
  - template: laravel
    vhost: "laravel.dev"
    path: "{{ ansible_env.HOME }}/Public/laravel"
    php: "7.1"

# Other configuration.
_devtool_docroots:
  - "{{ www_adminer_install_dir }}"
  - "{{ www_pimpmylog_install_dir }}"
  - "{{ www_dashboard_install_dir|default('') }}"

# The web server software to use. Can be either 'apache' or 'nginx'.
pbook_webserver: apache

# The database system to use. Can be either 'mysql' or 'pgsql'.
pbook_database: mysql

# The machine hostname. Useful when not defined with the chrx script.
pbook_hostname: localhost
pbook_domain: machina.dev
pbook_ip: 192.168.88.88
pbook_www_path: "/var/www/machina"

# Database credential settings.
pbook_db_name: homestead
pbook_db_user: homestead
pbook_db_password: secret

pbook_extras: [ "adminer", "pimpmylog", "mailhog" ]

#####################################################################
### ROLE VARS ###
#####################################################################

# Helper variable to configure the PHP-FPM connection for each Apache
# VirtualHost in the `apache_vhosts` list.
apache_vhost_php_fpm_parameters: |
    <FilesMatch \.php$>
      SetHandler "proxy:fcgi://{{ php_fpm_listen | default( '127.0.0.1:9000' ) }}"
    </FilesMatch>

# Apache VirtualHosts. Add one for each site you are running. For multisite deployments, you can point multiple servernames at one documentroot.
# View the apache Ansible Role README for more options.
apache_vhosts:
  - servername: "{{ pbook_domain }}"
    serveralias: "www.{{ pbook_domain }}"
    documentroot: "{{ pbook_www_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "adminer.{{ pbook_domain }}"
    documentroot: "{{ adminer_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "pimpmylog.{{ pbook_domain }}"
    documentroot: "{{ pimpmylog_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "dashboard.{{ pbook_domain }}"
    documentroot: "{{ www_dashboard_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"



# MySQL databases and users.
mysql_databases:
  - name: "{{ pbook_db_name }}"
    encoding: utf8mb4
    collation: utf8mb4_general_ci

mysql_users:
  - name: "{{ pbook_db_user }}"
    host: "%"
    password: "{{ pbook_db_password }}"
    priv: "{{ pbook_db_name }}.*:ALL"

# PostgreSQL databases and users.
postgresql_databases:
  - name: "{{ pbook_db_name }}"

postgresql_users:
  - name: "{{ pbook_db_user }}"
    password: "{{ pbook_db_password }}"
    db: "{{ pbook_db_name }}"
    priv: "ALL"
