---
# tasks file for thunderbird

- name: Check if thunderbird is already installed
  command: "dpkg-query -s {{ thunderbird_package_name }}"
  register: thunderbird_installed
  check_mode: no
  failed_when: thunderbird_installed.rc > 1
  changed_when: thunderbird_installed.rc == 1

# Install thunderbird
- name: Install thunderbird dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ thunderbird_dependencies | list }}"
  when: thunderbird_dependencies | length

- name: Ensure thunderbird is installed
  apt:
    name: "{{ thunderbird_package_name }}"
    state: present

- name: Ensure thunderbird extensions directory exist
  file:
    state: directory
    path: "{{ thunderbird_ext_dir }}"
    mode: 0755
  become: true

# Install Official Thunderbird extensions
- name: Fetch xpi download link from official thunderbird plugin page
  include_tasks: fetch-xpi-uri-official.yml
  vars:
    thunderbird_ext_url: "{{ item }}"
  with_items:
    - "{{ thunderbird_ext_official }}"

# Install Custom Thunderbird extensions
- name: Fetch xpi download link from custom urls
  include_tasks: fetch-xpi-uri-custom.yml
  vars:
    thunderbird_ext_url: "{{ item }}"
  with_items:
    - "{{ thunderbird_ext_custom }}"
