---
# defaults file for desktop

# Default desktop user.
desktop_user: "{{ master_user | default(ansible_env.SUDO_USER) }}"

# Default desktop home.
desktop_home: "{{ master_home | default(ansible_env.HOME) }}"

# Array of desktop apt package dependencies. These packages should be installed before all others.
desktop_dependencies:
  - xvfb
  - acpid
  - imagemagick

# Array of Personal Package Archives (PPAs) to add. Additional PPAs can be found at: https://launchpad.net/.
desktop_ppa:
  - { ppa: "ppa:yktooo/ppa",                       pkg: indicator-sound-switcher }
  # - { ppa: "ppa:dawidd0811/neofetch",              pkg: neofetch }
  # - { ppa: "ppa:kirillshkrogalev/ffmpeg-next",     pkg: ffmpeg }
  # - { ppa: "ppa:obsproject/obs-studio",            pkg: obs-studio }
  # - { ppa: "ppa:ubuntuhandbook1/audacity",         pkg: audacity }
  # - { ppa: "ppa:webupd8team/tor-browser",          pkg: tor-browser }
  # - { ppa: "ppa:notepadqq-team/notepadqq",         pkg: notepadqq }
  # - { ppa: "ppa:remmina-ppa-team/remmina-next",    pkg: remmina }
  # - { ppa: "ppa:remmina-ppa-team/remmina-next",    pkg: remmina-plugin-rdp }

# Array of gui desktop software packages to install
desktop_packages_gui:
  # - bleachbit
  # - filezilla
  # - gpick
  - meld
  - mpv
  # - font-manager
  # - transmission
  # - rhythmbox
  - ubuntu-restricted-extras

# Array of cli desktop software packages to install
desktop_packages_cli:
  - colortest
  - htop
  - httping
  - iftop
  - iotop
  - xclip
  - lastpass-cli
  - trash-cli

# Array of desktop apt packages to install.
desktop_packages: "{{ desktop_packages_gui + desktop_packages_cli }}"

# Sets the default application alternatives.
desktop_alternatives:
  # - { name: "x-www-browser", link: "/usr/bin/x-www-browser", path: "/usr/bin/firefox", priority: 250 }
  # - { name: "gnome-www-browser", link: "/usr/bin/gnome-www-browser", path: "/usr/bin/firefox", priority: 250 }
  - { name: "x-www-browser", link: "/usr/bin/x-www-browser", path: "/usr/bin/chromium-browser", priority: 250 }
  - { name: "gnome-www-browser", link: "/usr/bin/gnome-www-browser", path: "/usr/bin/chromium-browser", priority: 250 }
