---
# defaults file for desktop

# Determines the state for packages installed on the system. Available values are `present` or `latest`.
desktop_apt_state: latest

# Array of desktop apt package dependencies. These packages should be installed before all others.
desktop_apt_dependencies:
  - xvfb
  - acpid
  - imagemagick

# Array of Personal Package Archives (PPAs) to add. Additional PPAs can be found at: https://launchpad.net/.
desktop_apt_ppa:
  - ppa:yktooo/ppa
  - ppa:nilarimogard/webupd8
  - ppa:dawidd0811/neofetch

# Array of gui desktop software packages to install
desktop_apt_packages_gui:
  - bleachbit
  - filezilla
  - gpick
  - meld
  - mpv
  - font-manager
  - screenruler
  - transmission
  - typecatcher
  - lubuntu-software-center
  - indicator-sound-switcher
  - xfpanel-switch

# Array of cli desktop software packages to install
desktop_apt_packages_cli:
  - colortest
  - htop
  - httping
  - iftop
  - iotop
  - xclip
  - lastpass-cli
  - trash-cli
  - neofetch

# Array of desktop apt packages to install.
desktop_apt_packages: "{{ desktop_apt_packages_gui + desktop_apt_packages_cli }}"
