---
# defaults file for desktop

# Default desktop user.
desktop_user: "{{ config_user | default(ansible_env.SUDO_USER) }}"

# Default desktop home.
desktop_home: "{{ config_home | default(ansible_env.HOME) }}"

# Array of desktop apt package dependencies. These packages should be installed before all others.
desktop_dependencies:
  - xvfb
  - acpid
  - imagemagick

# Array of Personal Package Archives (PPAs) to add. Additional PPAs can be found at: https://launchpad.net/.
desktop_ppa:
  - { ppa: "ppa:yktooo/ppa", pkg: indicator-sound-switcher }

# Array of gui desktop software packages to install
desktop_packages_gui:
  - meld
  - mpv
  - ubuntu-restricted-extras

# Array of cli desktop software packages to install
desktop_packages_cli:
  - colortest
  - htop
  - httping
  - iftop
  - iotop
  - xclip
  - lastpass-cli
  - trash-cli

# Array of desktop apt packages to install.
desktop_packages: "{{ desktop_packages_gui + desktop_packages_cli }}"

# Sets the default application alternatives.
desktop_alternatives:
  # - { name: "x-www-browser", link: "/usr/bin/x-www-browser", path: "/usr/bin/firefox", priority: 250 }
  # - { name: "gnome-www-browser", link: "/usr/bin/gnome-www-browser", path: "/usr/bin/firefox", priority: 250 }
  - { name: "x-www-browser", link: "/usr/bin/x-www-browser", path: "/usr/bin/chromium-browser", priority: 250 }
  - { name: "gnome-www-browser", link: "/usr/bin/gnome-www-browser", path: "/usr/bin/chromium-browser", priority: 250 }
