---
# defaults file for desktop

# Determines the state for packages installed on the system. Available values are `present` or `latest`.
desktop_apt_state: latest

# Array of desktop apt package dependencies. These packages should be installed before all others.
desktop_apt_dependencies:
  - xvfb
  - acpid
  - imagemagick

# Array of Personal Package Archives (PPAs) to add. Additional PPAs can be found at: https://launchpad.net/.
desktop_apt_ppa:
  - ppa:yktooo/ppa
  - ppa:otto-kesselgulasch/gimp
  - ppa:inkscape.dev/stable
  - ppa:nilarimogard/webupd8

# Array of common desktop software packages to install
desktop_apt_packages_common:
  - bleachbit
  - filezilla
  - gpick
  - meld
  - mpv
  - font-manager
  - screenruler
  - transmission
  - typecatcher
  - gimp
  - gimp-plugin-registry
  - gimp-data-extras
  - inkscape
  - lubuntu-software-center
  - indicator-sound-switcher
  - xfpanel-switch
