---
# defaults file for node

# Set the version of Node.js to install ("0.10", "0.12", "4.x", "5.x", "6.x").
# Version numbers from Nodesource: https://github.com/nodesource/distributions
nodejs_version: "6.x"

# The user for whom the npm packages will be installed.
nodejs_install_npm_user: "{{ ansible_env.USER }}"

# The directory for global installations.
npm_config_prefix: "{{ ansible_env.HOME }}/.npm-global"

# Set to true to suppress the UID/GID switching when running package scripts. If set explicitly to false, then installing as a non-root user will fail.
npm_config_unsafe_perm: "false"

# Define a list of global packages to be installed with NPM.
nodejs_npm_global_packages:
  - name: gulp
  - name: bower
  - name: browser-sync
  - name: webpack
  - name: webpack-dev-server
  - name: yarn
  - name: grunt-cli
  - name: yo
  - name: npm-check-updates
  - name: phantomjs-prebuilt
  - name: casperjs
  - name: simplehttpserver
  - name: xlsx
  - name: webfont-dl
  - name: diff-so-fancy
  - name: less
  - name: node-sass

# The path of a package.json file used to install packages globally.
nodejs_package_json_path: ""
