---
# Variables listed here are applicable to all host groups
# http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

# Playbook provision scripts
mimetic_pre_provision_scripts: []
mimetic_post_provision_scripts: []

# The main provision user.
mimetic_user: "{{ ansible_env.USER }}"
mimetic_home: "{{ ansible_env.HOME }}"
mimetic_name: "{{ vault_name | default(none) }}"
mimetic_email: "{{ vault_email | default(none) }}"
mimetic_shell: bash

# Github/Bitbucket credentials
mimetic_github_user: "{{ vault_github_user | default('') }}"
mimetic_github_password: "{{ vault_github_password | default('') }}"
mimetic_bitbucket_user: "{{ vault_bitbucket_user | default('') }}"
mimetic_bitbucket_password: "{{ vault_bitbucket_password | default('') }}"

#####################################################################
### ROLE VARS ###
#####################################################################

# Admin role
admin_user: "{{ mimetic_user }}"
admin_home: "{{ mimetic_home }}"
admin_fullname: "{{ mimetic_name }}"

# SSH role
ssh_key_comment: "{{ mimetic_email }}"

# Git role
git_config_name: "{{ mimetic_name }}"
git_config_email: "{{ mimetic_email }}"
git_github_user: "{{ mimetic_github_user }}"
git_github_password: "{{ mimetic_github_password }}"
git_bitbucket_user: "{{ mimetic_bitbucket_user }}"
git_bitbucket_password: "{{ mimetic_bitbucket_password }}"

# Projects role
projects_git_name: "{{ mimetic_name }}"
projects_git_email: "{{ mimetic_email }}"

# Dotfiles role
dotfiles_git_name: "{{ mimetic_name }}"
dotfiles_git_email: "{{ mimetic_email }}"
