---
# Variables listed here are applicable to all host groups
# http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

# Playbook provision scripts
pbook_pre_provision_scripts: []
pbook_post_provision_scripts: []

# The main provision user.
pbook_user: "{{ ansible_env.USER }}"
pbook_home: "{{ ansible_env.HOME }}"
pbook_name: "{{ vault_name | default(none) }}"
pbook_email: "{{ vault_email | default(none) }}"
pbook_shell: bash

# Github/Bitbucket credentials
pbook_github_user: "{{ vault_github_user | default('') }}"
pbook_github_password: "{{ vault_github_password | default('') }}"
pbook_bitbucket_user: "{{ vault_bitbucket_user | default('') }}"
pbook_bitbucket_password: "{{ vault_bitbucket_password | default('') }}"

# The web server software to use. Can be either 'apache' or 'nginx'.
pbook_webserver: apache

# The database system to use. Can be either 'mysql' or 'pgsql'.
pbook_database: mysql

# The machine hostname. Useful when not defined with the chrx script.
pbook_hostname: localhost
pbook_domain: machina.dev
pbook_ip: 192.168.88.88
pbook_www_path: "/var/www/machina"

# Database credential settings.
pbook_db_name: homestead
pbook_db_user: homestead
pbook_db_password: secret

pbook_extras: [ "adminer", "pimpmylog", "mailhog" ]

#####################################################################
### ROLE VARS ###
#####################################################################

# Helper variable to configure the PHP-FPM connection for each Apache
# VirtualHost in the `apache_vhosts` list.
apache_vhost_php_fpm_parameters: |
    <FilesMatch \.php$>
      SetHandler "proxy:fcgi://{{ php_fpm_listen | default( '127.0.0.1:9000' ) }}"
    </FilesMatch>

# Apache VirtualHosts. Add one for each site you are running. For multisite deployments, you can point multiple servernames at one documentroot.
# View the apache Ansible Role README for more options.
apache_vhosts:
  - servername: "{{ pbook_domain }}"
    serveralias: "www.{{ pbook_domain }}"
    documentroot: "{{ pbook_www_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "adminer.{{ pbook_domain }}"
    documentroot: "{{ adminer_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "pimpmylog.{{ pbook_domain }}"
    documentroot: "{{ pimpmylog_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "dashboard.{{ pbook_domain }}"
    documentroot: "{{ www_dashboard_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

# Nginx hosts. Each site will get a server entry using the configuration defined
# here. Set the 'is_php' property for document roots that contain PHP apps.
nginx_vhosts:
  - server_name: "{{ pbook_domain }} www.{{ pbook_domain }}"
    root: "{{ pbook_www_path }}"
    is_php: true

  - server_name: "adminer.{{ pbook_domain }}"
    root: "{{ adminer_install_dir }}"
    is_php: true

  - server_name: "pimpmylog.{{ pbook_domain }}"
    root: "{{ pimpmylog_install_dir }}"
    is_php: true

  - server_name: "dashboard.{{ pbook_domain }}"
    root: "{{ www_dashboard_install_dir }}"
    is_php: true

# MySQL databases and users.
mysql_databases:
  - name: "{{ pbook_db_name }}"
    encoding: utf8mb4
    collation: utf8mb4_general_ci

mysql_users:
  - name: "{{ pbook_db_user }}"
    host: "%"
    password: "{{ pbook_db_password }}"
    priv: "{{ pbook_db_name }}.*:ALL"

# PostgreSQL databases and users.
postgresql_databases:
  - name: "{{ pbook_db_name }}"

postgresql_users:
  - name: "{{ pbook_db_user }}"
    password: "{{ pbook_db_password }}"
    db: "{{ pbook_db_name }}"
    priv: "ALL"
