---
# Variables listed here are applicable to all host groups
# http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

# Playbook provision scripts
mimetic_pre_provision_scripts: []
mimetic_post_provision_scripts: []

# The main provision user.
mimetic_user: "{{ ansible_env.USER }}"
mimetic_home: "{{ ansible_env.HOME }}"
mimetic_name: "{{ vault_name | default(none) }}"
mimetic_email: "{{ vault_email | default(none) }}"
mimetic_shell: bash

# Github/Bitbucket credentials
mimetic_github_user: "{{ vault_github_user | default('') }}"
mimetic_github_password: "{{ vault_github_password | default('') }}"
mimetic_bitbucket_user: "{{ vault_bitbucket_user | default('') }}"
mimetic_bitbucket_password: "{{ vault_bitbucket_password | default('') }}"
