---
# Variables listed here are applicable to all host groups
# http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

# Playbook provision scripts
master_pre_provision_scripts: []
master_post_provision_scripts: []

# General configuration
master_apt_cache_time: 86400

# The main provision user
master_user: "{{ vault_user | default(ansible_env.SUDO_USER, true) | default(ansible_env.USER, true) | default(ansible_user_id, true) }}"
master_password: "{{ vault_password | default(none) }}"
master_home: "/home/{{ master_user }}"
master_name: "{{ vault_name | default(none) }}"
master_email: "{{ vault_email | default(none) }}"
master_shell: bash

# Github/Bitbucket credentials
master_github_user: "{{ vault_github_user | default('') }}"
master_github_password: "{{ vault_github_password | default('') }}"
master_bitbucket_user: "{{ vault_bitbucket_user | default('') }}"
master_bitbucket_password: "{{ vault_bitbucket_password | default('') }}"

# Configuration options
master_security_enabled: false
master_dotfiles_enabled: false

# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, set this value to an empty set, e.g. `[]`.
master_installed_apps:
  - albert
  - audacity
  - bleachbit
  - blender
  - cherrytree
  - dbeaver
  - filezilla
  - gimp
  - inkscape
  - keepass
  - libreoffice
  - minecraft
  - notepadqq
  - obs
  - remmina
  - tor
  - transmission
