---
# tasks file for composer

- name: Check if Composer is installed
  become: yes
  stat:
    path: "{{ composer_path }}"
  register: composer_bin

- name: Get Composer installer signature
  become: yes
  uri:
    url: https://composer.github.io/installer.sig
    return_content: yes
  register: composer_installer_signature
  when: not composer_bin.stat.exists

- name: Download Composer installer
  become: yes
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
    checksum: "sha384:{{ composer_installer_signature.content }}"
  when: not composer_bin.stat.exists

- name: Run Composer installer
  become: yes
  command: php composer-installer.php
  args:
    chdir: /tmp
  when: not composer_bin.stat.exists

- name: Move Composer into globally-accessible location
  become: yes
  shell: "mv /tmp/composer.phar {{ composer_path }}"
  args:
    creates: "{{ composer_path }}"
  when: not composer_bin.stat.exists

- name: Update Composer to latest version
  shell: "php {{ composer_path }} self-update"
  register: composer_update
  changed_when: "'Updating to version' in composer_update.stdout"
  when: composer_keep_updated

# - name: Install Composer
#   become: yes
#   shell: "curl -sS https://getcomposer.org/installer | php && mv -f ./composer.phar {{ composer_path }}"
#   args:
#     creates: "{{ composer_path }}"
#     warn: false
#   when: not composer_bin.stat.exists

# - name: Make Composer executable
#   become: yes
#   file:
#     path: "{{ composer_path }}"
#     mode: 0755

- name: Ensure composer directory exists
  become: yes
  become_user: "{{ composer_user }}"
  file:
    path: "{{ composer_home_path }}"
    owner: "{{ composer_user }}"
    group: "{{ composer_group }}"
    state: directory

# - name: Add composer_home_path bin directory to global $PATH.
#   become: yes
#   template:
#     src: composer.sh.j2
#     dest: /etc/profile.d/composer.sh
#     mode: 0644

- name: Add composer_home_path bin directory to global $PATH
  become: yes
  become_user: "{{ composer_user }}"
  copy:
    dest: "{{ composer_home }}/.bash_path"
    content: "export PATH={{ composer_home_path }}/vendor/bin:$PATH"
    mode: 0664

# Composer global require
- name: Install configured globally-required packages
  command: >
    {{ composer_path }} global require {{ item.name }}:{{ item.release | default('@stable') }} --no-progress
    creates={{ composer_home_path }}/vendor/{{ item.name }}
  environment:
    COMPOSER_HOME: "{{ composer_home_path }}"
  become: yes
  become_user: "{{ composer_user }}"
  register: composer_global_require_result
  with_items: "{{ composer_global_packages }}"
  when: composer_global_packages|length > 0

# Install valet
# https://github.com/cpriego/valet-linux
- name: Install Laravel Valet
  shell: valet install
  become: yes
  # become_user: "{{ composer_user }}"

- name: Park sites
  shell: valet park
  args:
    chdir: "{{ composer_park }}"
  become: yes
  # become_user: "{{ composer_user }}"
