---
# tasks file for composer

- name: Set php_executable variable to a default if not defined
  set_fact:
    php_executable: php
  when: php_executable is not defined

- name: Check if Composer is installed
  stat:
    path: "{{ composer_path }}"
  register: composer_bin

- name: Download Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
  when: not composer_bin.stat.exists

- name: Run Composer installer
  command: >
    {{ php_executable }} composer-installer.php {% if composer_version != '' %} --version={{ composer_version }}{% endif %}
    chdir=/tmp
  when: not composer_bin.stat.exists

- name: Move Composer into globally-accessible location
  shell: >
    mv /tmp/composer.phar {{ composer_path }}
    creates={{ composer_path }}
  when: not composer_bin.stat.exists

- name: Update Composer to latest version (if configured)
  shell: >
    {{ php_executable }} {{ composer_path }} self-update
  register: composer_update
  changed_when: "'Updating to version' in composer_update.stdout"
  when: composer_keep_updated

- name: Ensure composer directory exists
  file:
    path: "{{ composer_home_path }}"
    owner: "{{ composer_home_owner }}"
    group: "{{ composer_home_group }}"
    state: directory

# Composer global packages
- name: Install configured globally-required packages
  command: >
    {{ composer_path }} global require {{ item.name }}:{{ item.release | default('@stable') }} --no-progress
    creates={{ composer_home_path }}/vendor/{{ item.name }}
  environment:
    COMPOSER_HOME: "{{ composer_home_path }}"
  become: yes
  become_user: "{{ composer_home_owner }}"
  register: composer_global_require_result
  with_items: "{{ composer_global_packages }}"
  when: composer_global_packages|length > 0

- name: Add composer_home_path bin directory to global $PATH
  template:
    src: composer.sh.j2
    dest: /etc/profile.d/composer.sh
    mode: 0644
  when: composer_add_to_path

# Composer project bin
- name: Add composer_project_path bin directory to global $PATH.
  template:
    src: composer-project.sh.j2
    dest: /etc/profile.d/composer-project.sh
    mode: 0644
  when: composer_add_project_to_path
