---
# tasks file for git

# Install Git
- name: Ensure git is installed
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ git_packages | list }}"

# Configure git
- name: Configure .gitconfig file
  template:
    src: gitconfig.j2
    dest: "{{ git_home }}/.gitconfig"
    owner: "{{ git_user }}"
    group: "{{ git_user }}"
  when: git_config

- name: Add .gitignore file
  template:
    src: gitignore.j2
    dest: "{{ git_home }}/{{ git_config.core.excludesfile | basename }}"
    owner: "{{ git_user }}"
    group: "{{ git_user }}"
  when: git_ignore and git_config.core is defined and git_config.core.excludesfile is defined

# Git Known Hosts
- name: Add Git Known hosts
  known_hosts:
    name: "{{ item.name }}"
    key: "{{ item.key | default(omit) }}"
    path: "{{ item.path | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  become: true
  become_user: "{{ git_user }}"
  with_items: "{{ git_known_hosts }}"

# Add SSH keys to Github & Bitbucket
- name: Download ssh-keyreg script
  get_url:
    url: https://raw.githubusercontent.com/b4b4r07/ssh-keyreg/master/bin/ssh-keyreg
    dest: /usr/local/bin/ssh-keyreg
    mode: 0555

- name: Check that the user ssh key exists
  stat:
    path: "{{ git_ssh_keyfile }}"
  register: git_ssh_key_exists

- name: Add SSH Key to GitHub
  shell: ssh-keyreg --path {{ git_ssh_keyfile }} --user {{ git_github_user }}:{{ git_github_password }} github
  become: true
  become_user: "{{ git_user }}"
  when:
    - git_github_user is defined and git_github_user != ''
    - git_github_password is defined and git_github_password != ''
    - git_ssh_key_exists.stat.exists == true

- name: Add SSH Key to Bitbucket
  shell: ssh-keyreg --path {{ git_ssh_keyfile }} --user {{ git_bitbucket_user }}:{{ git_bitbucket_password }} bitbucket
  become: true
  become_user: "{{ git_user }}"
  when:
    - git_bitbucket_user is defined and git_bitbucket_user != ''
    - git_bitbucket_password is defined and git_bitbucket_password != ''
    - git_ssh_key_exists.stat.exists == true

- name: Test github connection
  command: ssh -o StrictHostKeyChecking=no -T git@github.com
  register: github_test_var
  failed_when: github_test_var.rc not in [0, 1, 255]

- name: Display the Github test var
  debug:
    var: github_test_var
