---
# tasks file for themes

# Theme dependencies
- name: Install theme dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ theme_dependencies | list }}"

# Install Icons
- name: Add icon PPA repositories
  apt_repository:
    repo: "{{ item.ppa }}"
    state: present
  with_items: "{{ theme_icons }}"
  when: theme_icons | length

- name: Install icon PPA packages
  apt:
    name: "{{ item.pkg }}"
    state: present
  with_items: "{{ theme_icons }}"
  when: theme_icons | length

# Install LXDM
- name: Install lxdm dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ theme_lxdm_dependencies | list }}"

- name: Ensure lxdm.conf is present
  template:
    src: templates/lxdm.conf.j2
    dest: /etc/lxdm/lxdm.conf
    owner: root
    group: root
    mode: 0644
  become: yes

# Install Theme
- name: Install Arc-Theme
  git:
    repo: "{{ theme_arc_repo }}"
    dest: "{{ theme_home }}/.cache/arc-theme"
    update: yes
    accept_hostkey: yes
  register: arc_theme_git
  become: true
  become_user: "{{ theme_user }}"

- name: Build Arc-Theme
  command: ./autogen.sh --prefix=/usr --disable-transparency --disable-dark --disable-cinnamon --disable-gnome-shell --with-gnome=3.18
  args:
    chdir: "{{ theme_home }}/.cache/arc-theme"
  register: arc_theme_configure
  become: true
  become_user: "{{ theme_user }}"
  when: arc_theme_git.changed

- name: Make Arc-Theme
  command: make install
  args:
    chdir: "{{ theme_home }}/.cache/arc-theme"
  register: arc_theme_make
  when: arc_theme_git.changed

- name: Delete Arc-Theme cache
  file:
    path: "{{ theme_home }}/.cache/arc-theme"
    state: absent

# Theme config
- name: Set Theme settings
  shell: "{{ item }}"
  become: true
  become_user: "{{ theme_user }}"
  with_items:
    - xfconf-query -c xfwm4 -p /general/theme -n -t string -s "{{ theme_window }}"
    - xfconf-query -c xsettings -p /Net/ThemeName -n -t string -s "{{ theme_name }}"
    - xfconf-query -c xsettings -p /Net/IconThemeName -n -t string -s "{{ theme_iconset }}"
    - xfconf-query -c xsettings -p /Gtk/CursorThemeName -n -t string -s "{{ theme_cursor }}"
    - xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/workspace0/last-image -n -t string -s "{{ theme_wallpaper }}"

- name: Set Notify settings
  shell: "{{ item }}"
  become: true
  become_user: "{{ theme_user }}"
  with_items:
    - xfconf-query -c xfce4-notifyd -p /notify-location -n -t uint -s 2
    - xfconf-query -c xfce4-notifyd -p /theme -n -t string -s "{{ theme_notify }}"
    - xfconf-query -c xfce4-notifyd -p /expire-timeout -n -t int -s 3
