---
# tasks file for themes

# Theme dependencies
- name: Install theme dependencies
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ theme_dependencies | list }}"
  when: theme_dependencies | length

# Install Theme
- name: Install Arc-Theme
  git:
    repo: "{{ theme_arc_repo }}"
    dest: "{{ theme_home }}/.cache/arc-theme"
    update: yes
    accept_hostkey: yes
  register: arc_theme_git
  become: true
  become_user: "{{ theme_user }}"

- name: Build Arc-Theme
  command: ./autogen.sh --prefix=/usr --disable-transparency --disable-dark --disable-cinnamon --disable-gnome-shell --with-gnome=3.18
  args:
    chdir: "{{ theme_home }}/.cache/arc-theme"
  register: arc_theme_configure
  become: true
  become_user: "{{ theme_user }}"
  when: arc_theme_git.changed

- name: Make Arc-Theme
  become: yes
  command: make install
  args:
    chdir: "{{ theme_home }}/.cache/arc-theme"
  register: arc_theme_make
  when: arc_theme_git.changed

- name: Delete Arc-Theme cache
  become: yes
  file:
    path: "{{ theme_home }}/.cache/arc-theme"
    state: absent

# Install Black Theme
- name: Install Black-Arc-Theme
  git:
    repo: "{{ theme_black_repo }}"
    dest: "{{ theme_home }}/.cache/arc-black-ubuntu"
    update: yes
    accept_hostkey: yes
  register: black_theme_git
  become: true
  become_user: "{{ theme_user }}"

- name: Copy Black-Arc-Theme
  become: yes
  command: "cp -R {{ theme_home }}/.cache/arc-black-ubuntu* /usr/share/themes"
  when: black_theme_git.changed

- name: Delete Black-Arc-Theme cache
  become: yes
  file:
    path: "{{ theme_home }}/.cache/arc-black-ubuntu"
    state: absent

# Theme config
- name: Set Theme settings
  shell: "{{ item }}"
  become: true
  become_user: "{{ theme_user }}"
  with_items:
    - xfconf-query -c xfwm4 -p /general/theme -n -t string -s "{{ theme_window }}"
    - xfconf-query -c xsettings -p /Net/ThemeName -n -t string -s "{{ theme_name }}"
    - xfconf-query -c xsettings -p /Net/IconThemeName -n -t string -s "{{ theme_iconset }}"
    - xfconf-query -c xsettings -p /Gtk/CursorThemeName -n -t string -s "{{ theme_cursor }}"
    - xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/workspace0/last-image -n -t string -s "{{ theme_wallpaper }}"

- name: Set Notify settings
  shell: "{{ item }}"
  become: true
  become_user: "{{ theme_user }}"
  with_items:
    - xfconf-query -c xfce4-notifyd -p /notify-location -n -t uint -s 2
    - xfconf-query -c xfce4-notifyd -p /theme -n -t string -s "{{ theme_notify }}"
    - xfconf-query -c xfce4-notifyd -p /expire-timeout -n -t int -s 3
