---
# tasks file for flyway

- name: Download Flyway
  get_url:
    url: "{{ flyway_tgz_url }}"
    dest: "/tmp/{{ flyway_tgz }}"
    mode: 0644

- name: Unarchive Flyway
  unarchive:
    remote_src: yes
    src: "/tmp/{{ flyway_tgz }}"
    dest: "{{ flyway_parent_install_dir }}"
    creates: "{{ flyway_install_dir }}"

- name: Link Flyway
  file:
    src: "{{ flyway_install_dir }}"
    dest: "{{ flyway_install_link_dir }}"
    state: link

- name: Add Flyway to default path
  template:
    src: flyway.sh.j2
    dest: etc/profile.d/flyway.sh
    mode: 0644

- name: Cleanup Flyway
  file:
    path: "/tmp/{{ flyway_tgz }}"
    state: absent
