---
# tasks file for apps

# Install PPA Packages
- name: Add app PPA repositories
  become: yes
  apt_repository:
    repo: "{{ item.ppa }}"
    state: present
    validate_certs: yes
    update_cache: yes
  with_items: "{{ app_ppa }}"
  when: app_ppa | length
  register: app_repo

- name: Update apt cache if repo was added
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: app_repo.changed

- name: Install app PPA packages
  become: yes
  apt:
    name: "{{ item.pkg }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ app_ppa | list }}"
  when: app_ppa | length

# Install App Packages
- name: Install app software packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ app_packages | list }}"
  when: app_packages | length
