---
# defaults file for memcached

# The location of the memcached config file.
memcached_config_file: /etc/memcached.conf

# The location of the memcached log file.
memcached_log_file: /var/log/memcached.log

# Normally memcached does not log anything. Change to "-v" to enable logging or to "-vv" for debug logging.
memcached_log_verbosity: ""

# Memcached limits. The maximum amount of RAM `memcached` will consume (64MB is the default), and the maximum number of simultaneous connections memcached will handle.
memcached_memory_limit: 64
memcached_connections: 1024

# The default memcached user.
memcached_user: memcache

# The port and IP address (127.0.0.1 for localhost) on which Memcached will listen for requests.
memcached_port: 11211
memcached_listen_ip: 127.0.0.1
