---
# defaults file for vagrant

# The virtualbox version to install.
virtualbox_version: "5.2"

# Additional shared packages to install.
virtualbox_shared_packages:
  - dkms
  - linux-headers-amd64

# The vagrant version to install.
vagrant_version: "2.0.1"
