---
# handlers file for dotfiles

- name: checkout dotfiles
  become: true
  become_user: "{{ dotfiles_user }}"
  shell: "/usr/bin/git --git-dir=$HOME/{{ dotfiles_path }}/ --work-tree=$HOME checkout"
  args:
    chdir: "{{ dotfiles_home }}"
  notify: config dotfiles repo

- name: config dotfiles repo
  become: true
  become_user: "{{ dotfiles_user }}"
  shell: "/usr/bin/git --git-dir=$HOME/{{ dotfiles_path }}/ --work-tree=$HOME config --local status.showUntrackedFiles no"
  args:
    chdir: "{{ dotfiles_home }}"
