---
# defaults file for i3

i3_dependencies:
  - i3status
  - curl
  - git
  - gcc
  - automake
  - make
  # https://github.com/Airblader/i3/wiki/Compiling-&-Installing#debian-stretch
  # - libxcb-keysyms1-dev
  # - libpango1.0-dev
  # - libxcb-util0-dev
  - xcb
  # - libxcb1-dev
  # - libxcb-icccm4-dev
  # - libyajl-dev
  # - libev-dev
  # - libxcb-xkb-dev
  # - libxcb-cursor-dev
  # - libxkbcommon-dev
  # - libxcb-xinerama0-dev
  # - libxkbcommon-x11-dev
  # - libstartup-notification0-dev
  # - libxcb-randr0-dev
  # - libxcb-xrm0 # Not in Ubuntu
  # - libxcb-xrm-dev
  - libxcb1-dev
  - libxcb-keysyms1-dev
  - libpango1.0-dev
  - libxcb-util0-dev
  - libxcb-icccm4-dev
  - libyajl-dev
  - libstartup-notification0-dev
  - libxcb-randr0-dev
  - libev-dev
  - libxcb-cursor-dev
  - libxcb-xinerama0-dev
  - libxcb-xkb-dev
  - libxkbcommon-dev
  - libxkbcommon-x11-dev
  - autoconf
  - libxcb-xrm-dev # Added via PPA

i3_gaps_git_path: "{{ lookup('env','HOME') }}/.cache/i3-gaps-git"
i3_gaps_git_url: https://github.com/Airblader/i3

i3_bin_shared:
  - alsa-utils
  - dbus
  - exiv2
  - grabc
  - i3lock
  - imagemagick
  - libnotify-bin
  # - maim
  - procps
  - psmisc
  - scrot
  # - slop
  - sxiv
  - x11-utils
  - xdotool
  - zenity

# These tools will be downloaded to /usr/local/bin
i3_utils_bin_tools:
  - system-hibernate
  - system-reboot
  - system-shutdown
  - system-suspend
  - xcolorpick
  - ximage
  - xkiller
  - xlock
  - xscreenshot
  - xf86-audio
  - xf86-backlight

i3_systemd_shared:
  - alsa-utils
  - i3lock
  - imagemagick
  - libnotify-bin
  - procps
  - scrot

i3_utils_systemd_systemd_base_path: /usr/lib/systemd
#i3_utils_systemd_systemd_base_path: /etc/systemd

i3blocks_modules_shared_packages:
  - acpi
  - bash
  - cpufrequtils
  - curl
  - git
  - i3blocks
  - iproute2
  - lm-sensors
  - procps
  - pulseaudio-utils
  - wget
  - wireless-tools

i3blocks_modules_path: "{{ lookup('env','HOME') }}/.local/share/i3blocks-modules"
