---
# Remmina installation

- name: Add Remmina PPA repository
  become: yes
  apt_repository:
    repo: "ppa:remmina-ppa-team/remmina-next"
    state: present

- name: Ensure Remmina packages are installed
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - remmina
    - remmina-plugin-rdp
