---
# defaults file for ruby

# Default ruby user.
ruby_user: "{{ ansible_env.USER }}"

# Default ruby home.
ruby_home: "{{ ansible_env.HOME }}"

# Build dependencies for packages (will be installed with apt).
ruby_dependencies:
  - git-core
  - curl
  - zlib1g-dev
  - build-essential
  - libssl-dev
  - libreadline-dev
  - libyaml-dev
  - libsqlite3-dev
  - sqlite3
  - libxml2-dev
  - libxslt1-dev
  - libcurl4-openssl-dev
  - python-software-properties
  - libffi-dev

# Ruby version to install.
ruby_version: "2.4.2"

# Path to ruby rbenv file.
ruby_rbenv_profile: "{{ ruby_home }}/.{{ 'zshrc_local' if ansible_user_shell == '/bin/zsh' else 'bashrc' }}"

# A list of Ruby gems to install.
ruby_gems:
  - name: rails
    state: present
    version: 5.1.4
  - name: sass
  - name: boom
