---
# defaults file for python

# Default python user.
python_user: "{{ master_user | default(ansible_env.SUDO_USER) }}"

# Default python home.
python_home: "{{ master_home | default(ansible_env.HOME) }}"

# Build dependencies for packages (will be installed with apt).
python_dependencies:
  - build-essential
  - libssl-dev
  - libffi-dev

# Array of python apt packages.
python_packages:
  - python
  - python-pip
  - python-dev
  - python-apt
  - python-pycurl
  - python-minimal
  - python-setuptools
  - python-simplejson
  - python3
  - python3-pip
  - python3-setuptools

# Enable support for python 2.x.
python_legacy_support: yes

# Path to python pip executable.
python_pip_executable: "/usr/bin/pip{{ 2 if python_legacy_support else 3 }}"

# Array of python pip packages.
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A
