---
# tasks file for sublime

# Sublime Dependencies
- name: Ensure sublime dependencies are installed
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ sublime_dependencies | list }}"
  when: sublime_dependencies | length

# Sublime Installation
- name: Add sublime GPG key
  become: yes
  apt_key:
    url: "{{ sublime_gpg_key }}"
    id: "{{ sublime_apt_key }}"
    state: present
    validate_certs: yes
  register: sublime_key

- name: Update apt cache if key was added
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: sublime_key.changed

- name: Add sublime repository
  become: yes
  apt_repository:
    repo: "deb https://download.sublimetext.com/ apt/{{ sublime_repo_channel }}/"
    state: present
    filename: "sublime-text"
    validate_certs: yes
    update_cache: yes
  register: sublime_repo

- name: Update apt cache if repo was added
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: sublime_repo.changed

- name: Install latest sublime package
  become: yes
  apt:
    name: sublime-text
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  when: sublime_add_repo | succeeded

# Sublime Directories
- name: Ensure sublime config directory permissions
  file:
    state: directory
    path: "{{ sublime_config_dir }}"
    recurse: true
    mode: 0774
    owner: "{{ sublime_user }}"
    group: "{{ sublime_user }}"

- name: Ensure sublime directories exist
  file:
    state: directory
    path: "{{ item }}"
    mode: 0774
    recurse: true
    owner: "{{ sublime_user }}"
    group: "{{ sublime_user }}"
  with_items:
    - "{{ sublime_installed_pkgs_dir }}"
    - "{{ sublime_user_preferences_dir }}"
    - "{{ sublime_local_license_dir }}"

# Sublime Package Control
- name: Ensure Package Control.sublime-package present
  get_url:
    url: "{{ sublime_package_control_url }}"
    dest: "{{ sublime_installed_pkgs_dir }}/Package Control.sublime-package"
    timeout: 30
    mode: 0774
    owner: "{{ sublime_user }}"
    group: "{{ sublime_user }}"
  register: download_pkg_control
  until: download_pkg_control | succeeded
  retries: 10
  delay: 5

- name: Generate Package Control settings template for auto-install
  template:
    src: "Package Control.sublime-settings.j2"
    dest: "{{ sublime_user_preferences_dir }}/Package Control.sublime-settings"
    mode: 0774
    owner: "{{ sublime_user }}"
    group: "{{ sublime_user }}"
    backup: "{{ sublime_package_control_backup }}"

# Sublime License
- name: Copy Sublime license file
  copy:
    src: "License.sublime_license"
    dest: "{{ sublime_local_license_dir }}/License.sublime_license"
    owner: "{{ sublime_user }}"
    group: "{{ sublime_user }}"

# Sublime Preferences
- name: Copy Sublime preference file
  copy:
    src: "Preferences.sublime-settings"
    dest: "{{ sublime_user_preferences_dir }}/Preferences.sublime-settings"
    mode: 0774
    owner: "{{ sublime_user }}"
    group: "{{ sublime_user }}"

# Sublime Mousemap
- name: Copy Sublime mousemap file
  copy:
    src: "Default.sublime-mousemap"
    dest: "{{ sublime_user_preferences_dir }}/Default.sublime-mousemap"
    mode: 0774
    owner: "{{ sublime_user }}"
    group: "{{ sublime_user }}"
