---
# tasks file for common

# Upgrade System Packages
- name: Upgrade apt packages
  become: yes
  apt:
    upgrade: "{{ common_apt_upgrade_type }}"
    force: "{{ common_apt_upgrade_force }}"
    update_cache: yes
    cache_valid_time: "{{ common_apt_cache_time }}"
  when: common_apt_upgrade

# Update Package List
- name: Update apt packages
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: "{{ common_apt_cache_time }}"
  when: common_apt_update

# Remove packages
- name: Remove apt packages
  become: yes
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
    autoclean: yes
    autoremove: yes
  with_items: "{{ common_apt_remove_packages }}"

# Install Dependencies
- name: Install apt dependencies
  become: yes
  apt:
    name: "{{ item }}"
    state: "{{ common_apt_state }}"
    update_cache: yes
    cache_valid_time: "{{ common_apt_cache_time }}"
  with_items: "{{ common_apt_dependencies | list }}"

# Install Basic Packages
- name: Install base apt packages
  become: yes
  apt:
    name: "{{ item }}"
    state: "{{ common_apt_state }}"
    update_cache: yes
    cache_valid_time: "{{ common_apt_cache_time }}"
  with_items: "{{ common_apt_add_packages | list }}"

# Install Custom Packages
- name: Install extra apt packages (if any are configured)
  become: yes
  apt:
    name: "{{ item }}"
    state: "{{ common_apt_state }}"
    update_cache: yes
    cache_valid_time: "{{ common_apt_cache_time }}"
  with_items: "{{ common_apt_custom_packages | list }}"
  when: common_apt_custom_packages | length
