---
# tasks file for beanstalkd

- name: Install Beanstalkd package
  apt:
    name: "{{ beanstalkd_package }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ aptcachetime | default(3600) }}"

- name: Configure Beanstalkd options
  lineinfile:
    dest: /etc/default/beanstalkd
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^#?START", line: "START=yes" }
  notify: restart beanstalkd

- name: "Ensure Beanstalkd is {{ beanstalkd_start | ternary('started','stopped') }}"
  service:
    name: beanstalkd
    state: "{{ beanstalkd_start | ternary('restarted','stopped') }}"
    enabled: "{{ beanstalkd_service_enabled }}"
