---
# defaults file for postgresql

postgresql_version: 9.5

# Library used by Ansible to communicate with PostgreSQL. If you are using Python 3 (e.g. set via `ansible_python_interpreter`), you should change this to `python3-psycopg2`.
postgresql_python_library: python-psycopg2

# Used to generate the locales used by PostgreSQL databases.
postgresql_locale: "en_US.UTF-8"

postgresql_root_user: root

postgresql_root_password: root

postgresql_ssl: true

postgresql_config:
  data_directory: /var/lib/postgresql/9.5/main
  # change to * to bind to 0.0.0.0
  listen_addresses: 127.0.0.1
  max_connections: 100
  port: 5432
  # defaults to 20%
  shared_buffers: "{{ (ansible_memtotal_mb / 5) | int }}"
  timezone: UTC

# The defaults:
# TYPE  DATABASE USER     ADDRESS      METHOD
# local all      postgres              trust
# host  all      all      127.0.0.1/32 md5
#
# - type: local|host
#   user: postgresql user - defaults to "all"
#   database: database name - defaults to "all"
#   address: address - defaults to ""
#   auth_method: auth metod - defaults to "md5"
#   auth_options: additional auth option - defaults to ""
postgresql_hba_entries:
  - { type: local, user: postgres, auth_method: trust }
  - { type: host, address: 127.0.0.1/32 }
