---
# defaults file for vscode

# Default vscode user.
vscode_user: "{{ master_user | default(ansible_env.SUDO_USER) }}"

# Default vscode home.
vscode_home: "{{ master_home | default(ansible_env.HOME) }}"
