---
# tasks file for inkscape

- name: Configure the Inkscape PPA
  apt_repository:
    repo: ppa:inkscape.dev/stable
    state: present
  register: inkscape_add_apt_repo

- name: Ensure Inkscape is installed
  apt:
    name: inkscape
    state: latest
  when: inkscape_add_apt_repo | succeeded
