---
# tasks file for blackfire

- name: Add packagecloud apt key
  apt_key:
    url: https://packagecloud.io/gpg.key
    state: present

- name: Add packagecloud repository
  apt_repository:
    repo: "{{ item }}"
    state: present
  register: blackfire_repos
  with_items:
    - "deb http://packages.blackfire.io/debian any main"

- name: Update apt caches after repo is added
  apt:
    update_cache: yes
  when: blackfire_repos.changed

- name: Ensure Blackfire packages are installed
  package:
    name: "{{ blackfire_packages }}"
    state: present
