---
# tasks file for blackfire

- name: Add packagecloud apt key
  apt_key:
    url: "{{ blackfire_gpg_key_url }}"
    state: present

- name: Add packagecloud repository
  apt_repository:
    repo: "{{ item }}"
    state: present
  register: packagecloud_repos
  with_items:
    - "deb http://packages.blackfire.io/debian any main"

- name: Update apt caches after repo is added
  apt:
    update_cache: yes
  when: packagecloud_repos.changed

- name: Ensure Blackfire packages are installed
  package:
    name: "{{ blackfire_packages }}"
    state: present
  # notify: restart webserver

- name: Restart Apache
  service:
    name: apache2
    state: restarted

- name: "Ensure Blackfire.io is {{ blackfire_start | ternary('started','stopped') }}"
  service:
    name: blackfire-agent
    state: "{{ blackfire_start | ternary('restarted','stopped') }}"
    enabled: "{{ blackfire_service_enabled }}"
