---
# tasks file for memcached

- name: Install Memcached
  apt:
    name: memcached
    state: present
    update_cache: yes
    cache_valid_time: 86400
  register: memcached_install

# Configure Memcached
- name: Copy Memcached configuration
  template:
    src: memcached.conf.j2
    dest: "{{ memcached_config_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart memcached

- name: Set the max open file descriptors
  sysctl:
    name: fs.file-max
    value: "{{ memcached_fs_file_max }}"
    state: present

- name: Ensure Memcached is started and set to run on startup
  service:
    name: memcached
    state: started
    enabled: yes
