---
# defaults file for php

# Default php user.
php_user: "{{ config_user | default(ansible_env.SUDO_USER) }}"

# Default php home.
php_home: "{{ config_home | default(ansible_env.HOME) }}"

php_version: "7.2"

# Build dependencies for packages (will be installed with apt).
php_packages:
  - "php{{ php_version }}"
  - "php{{ php_version }}-bcmath"
  - "php{{ php_version }}-bz2"
  - "php{{ php_version }}-cgi"
  - "php{{ php_version }}-cli"
  - "php{{ php_version }}-common"
  - "php{{ php_version }}-curl"
  - "php{{ php_version }}-dev"
  - "php{{ php_version }}-gd"
  - "php{{ php_version }}-intl"
  - "php{{ php_version }}-imagick"
  - "php{{ php_version }}-imap"
  - "php{{ php_version }}-json"
  - "php{{ php_version }}-ldap"
  - "php{{ php_version }}-mbstring"
  # - "php{{ php_version }}-mcrypt"
  - "php{{ php_version }}-mysql"
  - "php{{ php_version }}-opcache"
  - "php{{ php_version }}-readline"
  - "php{{ php_version }}-soap"
  - "php{{ php_version }}-sqlite3"
  - "php{{ php_version }}-xdebug"
  - "php{{ php_version }}-xml"
  - "php{{ php_version }}-xmlrpc"
  - "php{{ php_version }}-yaml"
  - "php{{ php_version }}-zip"
  - "php-pear"
