---
# tasks file for gimp

- name: Check if gimp is already installed
  command: "dpkg-query -s {{ gimp_package_name }}"
  register: gimp_installed
  check_mode: no
  failed_when: gimp_installed.rc > 1
  changed_when: gimp_installed.rc == 1

# Gimp Installation
- name: Add Gimp repository
  apt_repository:
    repo: ppa:otto-kesselgulasch/gimp
    state: present
  register: gimp_add_apt_repo

- name: Install Gimp
  apt:
    name: "{{ gimp_package_name }}"
    state: latest
  when: gimp_add_apt_repo | succeeded

- name: Install Gimp Extras
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ gimp_plugin_packages }}"
  when: gimp_add_apt_repo | succeeded

# - name: Ensure gimp is installed
#   apt:
#     name: "{{ item }}"
#     state: latest
#   with_items:
#     - gimp
#     - gimp-plugin-registry
#     - gimp-data-extras
#     - gimp-ufraw

# Gimp Configuration
- name: Ensure gimp configuration directories exist
  file:
    state: directory
    path: "{{ item }}"
    mode: 0755
  with_items:
    - "{{ gimp_config_dir }}"
    - "{{ gimp_theme_dir }}"

- name: Ensure initial configurations are applied
  copy:
    src: "files/{{ item.name }}"
    dest: "{{ gimp_config_dir }}/{{ item.name }}"
    mode: "{{ item.mode }}"
  when: gimp_installed.rc == 1
  with_items:
    - { mode: '0600', name: gimprc }
    - { mode: '0644', name: gtkrc }
    - { mode: '0644', name: menurc }
    - { mode: '0600', name: sessionrc }
    - { mode: '0600', name: toolrc }

- name: Ensure gimp photoshop theme is downloaded
  unarchive:
    src: "{{ gimp_theme_url }}"
    dest: "{{ gimp_theme_dir }}"
    remote_src: yes
    #mode: 0755

# Install Gimp
# - name: Add Gimp repository
#   apt_repository:
#     repo: ppa:otto-kesselgulasch/gimp
#     state: present
#   register: gimp_add_apt_repo

# - name: Install Gimp
#   apt:
#     name: "{{ item }}"
#     state: latest
#   with_items:
#     - gimp
#     - gimp-plugin-registry
#     - gimp-data-extras
#   when: gimp_add_apt_repo | succeeded

# - name: Ensure Gimp directory exists
#   file:
#     state: directory
#     path: "{{ gimp_home }}/.gimp-2.8"
#     mode: 0755
#     owner: "{{ gimp_user }}"
#     group: "{{ gimp_user }}"

# - name: Add Gimp configuration
#   lineinfile:
#     dest: "{{ gimp_home }}/.gimp-2.8/sessionrc"
#     regexp: "{{ item.param }}"
#     line: "{{ item.value }}"
#     create: true
#   with_items :
#     - { param: "single-window-mode", value: "(single-window-mode yes)" }
#     - { param: "default-snap-to-canvas", value: "(default-snap-to-canvas yes)" }
#     - { param: "default-snap-to-grid", value: "(default-snap-to-grid yes)" }
#     - { param: "hide-docks", value: "(hide-docks no)" }
#     - { param: "last-tip-shown", value: "(last-tip-shown 0)" }
#   become: true
#   become_user: "{{ gimp_user }}"
