---
# tasks file for ruby

# Install Dependencies
- name: Ensure ruby dependencies are installed
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ ruby_dependencies | list }}"
  when: ruby_dependencies | length

# Install Ruby via Brightbox PPA
- name: Add ruby PPA repository
  become: yes
  apt_repository:
    repo: ppa:brightbox/ruby-ng
    state: present
    validate_certs: yes
    update_cache: yes
  register: ruby_repo

- name: Update apt cache if repo was added
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ruby_repo.changed

- name: Install ruby software packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ ruby_packages | list }}"
  when: ruby_packages | length

- name : Set ruby version
  shell: ruby-switch --set ruby{{ ruby_version | truncate(3,True,'',0) }}
  become: yes

# Install RubyGems
- name: Install bundler
  become: yes
  gem:
    name: bundler
    state: present
    user_install: no

- name: Install global ruby gems
  become: yes
  gem:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    user_install: "{{ item.user_install | default('no') }}"
    executable: "{{ item.executable | default(omit) }}"
  with_items: "{{ ruby_gems }}"
