---
# defaults file for user

# Default admin full name.
user_fullname: "{{ pbook_name }}"

# Secondary groups for the admin user.
user_groups: [www-data]

# Default admin users shell. Possible values include `bash` or `zsh`.
user_shell: "{{ pbook_shell }}"

# XDG user directories. To remove a folder, set its value to "$HOME".
user_xdg_directories:
  - { name: DESKTOP,     path: "$HOME/Desktop",   dir: Desktop,   state: directory }
  - { name: DOWNLOAD,    path: "$HOME/Downloads", dir: Downloads, state: directory }
  - { name: TEMPLATES,   path: "$HOME/Templates", dir: Templates, state: directory }
  - { name: PUBLICSHARE, path: "$HOME/Public",    dir: Public,    state: directory }
  - { name: DOCUMENTS,   path: "$HOME/Documents", dir: Documents, state: directory }
  - { name: MUSIC,       path: "$HOME",           dir: Music,     state: absent  }
  - { name: PICTURES,    path: "$HOME",           dir: Pictures,  state: absent  }
  - { name: VIDEOS,      path: "$HOME",           dir: Videos,    state: absent  }

# Default ssh public & private key files.
user_ssh_privkey: "{{ ansible_env.HOME }}/.ssh/id_rsa"
user_ssh_pubkey: "{{ ansible_env.HOME }}/.ssh/id_rsa.pub"

# SSH key parameter
user_ssh_key_comment: "{{ pbook_email }}"
