---
# tasks file for mailhog

- name: Check MailHog version
  command: "mailhog --version"
  register: mailhog_check
  ignore_errors: true
  failed_when: false
  changed_when: false

- name: Cleanup MailHog existing installation
  file:
    path: "{{ mailhog_install_dir }}/mailhog"
    state: absent
  when: mailhog_check | failed
  ignore_errors: true
  failed_when: false
  changed_when: false

# Install and configure MailHog
- name: Ensure mailhog install directory exists
  file:
    path: "{{ mailhog_install_dir }}"
    owner: root
    group: root
    state: directory
    mode: 0755

- name: Download MailHog and mhsendmail binaries
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - url: "{{ mailhog_binary_url }}"
      dest: "{{ mailhog_install_dir }}/mailhog"
    - url: "{{ mhsendmail_binary_url }}"
      dest: "{{ mailhog_install_dir }}/mhsendmail"

- name: Copy mailhog systemd unit file into place (for systemd systems)
  template:
    src: mailhog.unit.j2
    dest: /etc/systemd/system/mailhog.service
    owner: root
    group: root
    mode: 0755
  when: "ansible_service_mgr == 'systemd'"

- name: Ensure mailhog is enabled and will start on boot
  service:
    name: mailhog
    state: started
    enabled: yes
