---
# handlers file for php

- name: restart webserver
  service:
    name: "{{ php_webserver_daemon }}"
    state: restarted
  notify: restart php-fpm

- name: restart php-fpm
  service:
    name: php7.1-fpm
    state: restarted
