---
# tasks file for fonts

# Font Dependencies
- name: Ensure font dependencies are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ font_dependencies | list }}"

# Font Installation
- name: Ensure font directory exists
  file:
    path: "{{ lookup('env','HOME') }}/.local/share/fonts/{{ item.name }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ font_packages }}"
  notify: update font-cache

# Install Font Packages
- name: Install font software packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ font_apt_packages | list }}"
  when: font_apt_packages | length

- name: Ensure fonts are downloaded
  get_url:
    url: "{{ item.url }}"
    dest: "{{ lookup('env','HOME') }}/.local/share/fonts/{{ item.name }}/{{ item.url | basename | replace('%20', ' ') }}"
    mode: 0644
    force: yes
    timeout: 30
  register: task_result
  until: task_result | succeeded
  retries: 10
  delay: 5
  with_items:
    - "{{ font_packages }}"
  notify: update font-cache

# - name: Ensure terminus fonts are downloaded
#   get_url:
#     url: "{{ item }}"
#     dest: "{{ font_terminus_font_path }}/{{ item | basename | replace('%20', ' ') }}"
#     mode: 0644
#     force: yes
#     timeout: 30
#   register: task_result
#   until: task_result | succeeded
#   retries: 10
#   delay: 5
#   with_items:
#     - "{{ font_terminus_bold_urls }}"
#     - "{{ font_terminus_bold_italic_urls }}"
#     - "{{ font_terminus_italic_urls }}"
#     - "{{ font_terminus_regular_urls }}"
#   notify: update font-cache

# Ubuntu font installation
- name: fetch ubuntu font info
  uri:
    url: https://design.ubuntu.com/font/
    method: GET
    follow_redirects: yes
    return_content: yes
  register: font_ubuntu_raw
  check_mode: no

- name: set ubuntu font url
  set_fact:
    font_ubuntu_zip: "{{ font_ubuntu_raw.content | regex_search(qry) }}"
  vars:
    qry: 'https://assets.ubuntu.com/.*-ubuntu-font-family-[.0-9]+\.zip'
  check_mode: no

# Unarchive module seems buggy:
# When directory already exists user cannot
# chown group, even if it is his own, therefore run as root.
- name: get current user
  shell: "whoami"
  register: font_ubuntu_user
  check_mode: no
  changed_when: False

- name: get current user group
  shell: "getent group {{ font_ubuntu_user.stdout }} | awk -F ':' '{print $1}'"
  register: font_ubuntu_group
  check_mode: no
  changed_when: False

- name: ensure ubuntu font is downloaded
  unarchive:
    src: "{{ font_ubuntu_zip }}"
    dest: "{{ lookup('env','HOME') }}/.local/share/fonts"
    remote_src: yes
    owner: "{{ font_ubuntu_user.stdout }}"
    group: "{{ font_ubuntu_group.stdout }}"
    #mode: 0755
  become: yes
  notify: update font-cache

# Make sure the handler runs now and not at the end of the playbook
- meta: flush_handlers
